// vue/components/Badge.vue
<template>
  <component :is="component" :class="c.base[size]">
    <slot />
  </component>
</template>
<script>
  import { computed } from 'vue';
  import { useContext } from '../shared/use-context.js';
  import { BadgeClasses } from '../../shared/esm/classes/BadgeClasses.js';
  import { BadgeColors } from '../../shared/esm/colors/BadgeColors.js';
  import { themeClasses } from '../shared/use-theme-classes.js';

  export default {
    name: 'k-badge',
    props: {
      component: {
        type: String,
        default: 'span',
      },
      small: {
        type: Boolean,
        default: false,
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
    },
    setup(props) {
      const context = useContext();
      const useThemeClasses = themeClasses(context);
      const colors = computed(() => BadgeColors(props.colors || {}));

      const size = computed(() => (props.small ? 'sm' : 'md'));

      const c = useThemeClasses(props, () => BadgeClasses(props, colors.value));

      return {
        c,
        size,
      };
    },
  };
</script>

// react/cjs/components/Badge.js
"use strict";

exports.__esModule = true;
exports.default = void 0;
var _react = _interopRequireWildcard(require("react"));
var _BadgeClasses = require("../../../shared/cjs/classes/BadgeClasses.js");
var _BadgeColors = require("../../../shared/cjs/colors/BadgeColors.js");
var _useThemeClasses = require("../shared/use-theme-classes.js");
function _getRequireWildcardCache(e) { if ("function" != typeof WeakMap) return null; var r = new WeakMap(), t = new WeakMap(); return (_getRequireWildcardCache = function (e) { return e ? t : r; })(e); }
function _interopRequireWildcard(e, r) { if (!r && e && e.__esModule) return e; if (null === e || "object" != typeof e && "function" != typeof e) return { default: e }; var t = _getRequireWildcardCache(r); if (t && t.has(e)) return t.get(e); var n = { __proto__: null }, a = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var u in e) if ("default" !== u && {}.hasOwnProperty.call(e, u)) { var i = a ? Object.getOwnPropertyDescriptor(e, u) : null; i && (i.get || i.set) ? Object.defineProperty(n, u, i) : n[u] = e[u]; } return n.default = e, t && t.set(e, n), n; }
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const Badge = /*#__PURE__*/(0, _react.forwardRef)((props, ref) => {
  const {
    component = 'span',
    className,
    colors: colorsProp,
    small,
    ios,
    material,
    // Children
    children,
    // Rest
    ...rest
  } = props;
  const elRef = (0, _react.useRef)(null);
  (0, _react.useImperativeHandle)(ref, () => ({
    el: elRef.current
  }));
  const Component = component;
  const attrs = {
    ...rest
  };
  const themeClasses = (0, _useThemeClasses.useThemeClasses)({
    ios,
    material
  });
  const colors = (0, _BadgeColors.BadgeColors)(colorsProp);
  const size = small ? 'sm' : 'md';
  const c = themeClasses((0, _BadgeClasses.BadgeClasses)(props, colors), className);
  return /*#__PURE__*/_react.default.createElement(Component, _extends({
    ref: elRef,
    className: c.base[size]
  }, attrs), children);
});
Badge.displayName = 'Badge';
var _default = exports.default = Badge;
