// svelte/components/BreadcrumbsItem.svelte
<script>
  import { BreadcrumbsItemClasses } from '../../shared/esm/classes/BreadcrumbsItemClasses.js';
  import { BreadcrumbsItemColors } from '../../shared/esm/colors/BreadcrumbsItemColors.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  let className = undefined;
  export { className as class };
  export let ios = undefined;
  export let material = undefined;

  let colorsProp = undefined;
  export { colorsProp as colors };

  export let onClick = undefined;

  export let active = false;

  const dark = useDarkClasses();

  $: colors = BreadcrumbsItemColors(colorsProp, dark);

  $: c = useThemeClasses(
    { ios, material },
    BreadcrumbsItemClasses({ active }, colors),
    className,
    (v) => (c = v)
  );
</script>

<div
  class={c.base}
  {...$$restProps}
  role="menuitem"
  tabindex="0"
  on:click={onClick}
>
  <slot />
</div>

// react/cjs/components/BreadcrumbsItem.js
"use strict";

exports.__esModule = true;
exports.default = void 0;
var _react = _interopRequireWildcard(require("react"));
var _BreadcrumbsItemClasses = require("../../../shared/cjs/classes/BreadcrumbsItemClasses.js");
var _BreadcrumbsItemColors = require("../../../shared/cjs/colors/BreadcrumbsItemColors.js");
var _useDarkClasses = require("../shared/use-dark-classes.js");
var _useThemeClasses = require("../shared/use-theme-classes.js");
function _getRequireWildcardCache(e) { if ("function" != typeof WeakMap) return null; var r = new WeakMap(), t = new WeakMap(); return (_getRequireWildcardCache = function (e) { return e ? t : r; })(e); }
function _interopRequireWildcard(e, r) { if (!r && e && e.__esModule) return e; if (null === e || "object" != typeof e && "function" != typeof e) return { default: e }; var t = _getRequireWildcardCache(r); if (t && t.has(e)) return t.get(e); var n = { __proto__: null }, a = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var u in e) if ("default" !== u && {}.hasOwnProperty.call(e, u)) { var i = a ? Object.getOwnPropertyDescriptor(e, u) : null; i && (i.get || i.set) ? Object.defineProperty(n, u, i) : n[u] = e[u]; } return n.default = e, t && t.set(e, n), n; }
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const BreadcrumbsItem = /*#__PURE__*/(0, _react.forwardRef)((props, ref) => {
  const {
    component = 'div',
    className,
    ios,
    material,
    colors: colorsProp,
    active,
    // Children
    children,
    // Rest
    ...rest
  } = props;
  const elRef = (0, _react.useRef)(null);
  (0, _react.useImperativeHandle)(ref, () => ({
    el: elRef.current
  }));
  const Component = component;
  const attrs = {
    ...rest
  };
  const themeClasses = (0, _useThemeClasses.useThemeClasses)({
    ios,
    material
  });
  const dark = (0, _useDarkClasses.useDarkClasses)();
  const colors = (0, _BreadcrumbsItemColors.BreadcrumbsItemColors)(colorsProp, dark);
  const c = themeClasses((0, _BreadcrumbsItemClasses.BreadcrumbsItemClasses)({
    ...props
  }, colors), className);
  return /*#__PURE__*/_react.default.createElement(Component, _extends({
    ref: elRef,
    className: c.base,
    role: "menuitem",
    tabIndex: "0"
  }, attrs), children);
});
BreadcrumbsItem.displayName = 'BreadcrumbsItem';
var _default = exports.default = BreadcrumbsItem;
