// svelte/components/DialogButton.svelte
<script>
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useTheme } from '../shared/use-theme.js';

  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { DialogButtonClasses } from '../../shared/esm/classes/DialogButtonClasses.js';
  import { DialogButtonColors } from '../../shared/esm/colors/DialogButtonColors.js';
  import Button from './Button.svelte';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let component = 'button'; // or 'a'

  export let disabled = false;
  export let strong = undefined;
  export let strongIos = undefined;
  export let strongMaterial = undefined;

  export let onClick = undefined;

  let theme;
  theme = useTheme({}, (v) => (theme = v));

  $: isStrong =
    typeof strong === 'undefined'
      ? theme === 'ios'
        ? strongIos
        : strongMaterial
      : strong;

  $: attrs = {
    ...$$restProps,
  };

  const dark = useDarkClasses();

  $: colors = DialogButtonColors(colorsProp, dark);

  $: c = useThemeClasses(
    { ios, material },
    DialogButtonClasses(
      { disabled, strong: isStrong },
      colors,
      className,
      dark
    ),
    '',
    (v) => (c = v)
  );
</script>

{#if theme === 'ios'}
  {#if typeof component === 'string'}
    <svelte:element
      this={component}
      class={c.base}
      {disabled}
      {...attrs}
      role="button"
      tabindex="0"
      on:click={onClick}
    >
      <slot />
    </svelte:element>
  {:else}
    <svelte:component
      this={component}
      class={c.base}
      {disabled}
      {...attrs}
      on:click={onClick}
    >
      <slot />
    </svelte:component>
  {/if}
{:else}
  <Button
    {component}
    inline
    rounded
    {disabled}
    clear={!isStrong}
    class={className}
    {onClick}
    {...attrs}
  >
    <slot />
  </Button>
{/if}

// react/cjs/components/DialogButton.js
"use strict";

exports.__esModule = true;
exports.default = void 0;
var _react = _interopRequireWildcard(require("react"));
var _useTheme = require("../shared/use-theme.js");
var _useThemeClasses = require("../shared/use-theme-classes.js");
var _useDarkClasses = require("../shared/use-dark-classes.js");
var _DialogButtonClasses = require("../../../shared/cjs/classes/DialogButtonClasses.js");
var _DialogButtonColors = require("../../../shared/cjs/colors/DialogButtonColors.js");
var _Button = _interopRequireDefault(require("./Button.js"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { default: e }; }
function _getRequireWildcardCache(e) { if ("function" != typeof WeakMap) return null; var r = new WeakMap(), t = new WeakMap(); return (_getRequireWildcardCache = function (e) { return e ? t : r; })(e); }
function _interopRequireWildcard(e, r) { if (!r && e && e.__esModule) return e; if (null === e || "object" != typeof e && "function" != typeof e) return { default: e }; var t = _getRequireWildcardCache(r); if (t && t.has(e)) return t.get(e); var n = { __proto__: null }, a = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var u in e) if ("default" !== u && {}.hasOwnProperty.call(e, u)) { var i = a ? Object.getOwnPropertyDescriptor(e, u) : null; i && (i.get || i.set) ? Object.defineProperty(n, u, i) : n[u] = e[u]; } return n.default = e, t && t.set(e, n), n; }
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const DialogButton = /*#__PURE__*/(0, _react.forwardRef)((props, ref) => {
  const {
    component = 'button',
    className,
    colors: colorsProp,
    ios,
    material,
    disabled,
    strong,
    strongIos,
    strongMaterial,
    // Children
    children,
    // Rest
    ...rest
  } = props;
  const elRef = (0, _react.useRef)(null);
  (0, _react.useImperativeHandle)(ref, () => ({
    el: elRef.current
  }));
  const attrs = {
    ...rest
  };
  const theme = (0, _useTheme.useTheme)({
    ios,
    material
  });
  const themeClasses = (0, _useThemeClasses.useThemeClasses)({
    ios,
    material
  });
  const dark = (0, _useDarkClasses.useDarkClasses)();
  const colors = (0, _DialogButtonColors.DialogButtonColors)(colorsProp, dark);
  const isStrong = typeof strong === 'undefined' ? theme === 'ios' ? strongIos : strongMaterial : strong;
  const c = themeClasses((0, _DialogButtonClasses.DialogButtonClasses)({
    ...props,
    strong: isStrong
  }, colors, dark), className);
  const Component = component;
  if (theme === 'ios') return /*#__PURE__*/_react.default.createElement(Component, _extends({
    className: c.base,
    disabled: disabled,
    role: "button",
    tabIndex: "0"
  }, attrs), children);
  return /*#__PURE__*/_react.default.createElement(_Button.default, _extends({
    component: component,
    inline: true,
    rounded: true,
    disabled: disabled,
    clear: !isStrong,
    className: className
  }, attrs), children);
});
DialogButton.displayName = 'DialogButton';
var _default = exports.default = DialogButton;
