// svelte/components/Fab.svelte
<script>
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useTouchRipple } from '../shared/use-touch-ripple.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { FabClasses } from '../../shared/esm/classes/FabClasses.js';
  import { FabColors } from '../../shared/esm/colors/FabColors.js';
  import { printText } from '../shared/print-text.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let component = 'a'; // or 'button'

  export let href = undefined;
  export let text = undefined;
  export let textPosition = 'after';
  export let touchRipple = true;

  export let onClick = undefined;

  const rippleEl = { current: null };

  const dark = useDarkClasses();

  $: useTouchRipple(rippleEl, touchRipple);

  $: colors = FabColors(colorsProp, dark);

  $: c = useThemeClasses(
    { ios, material },
    FabClasses({}, colors),
    className,
    (v) => (c = v)
  );
</script>

{#if typeof component === 'string'}
  <svelte:element
    this={component}
    class={text ? c.base.withText : c.base.iconOnly}
    {href}
    bind:this={rippleEl.current}
    role="button"
    tabindex="0"
    on:click={onClick}
    {...$$restProps}
  >
    {#if (text || $$slots.text) && textPosition === 'before'}
      <span class={c.text}>{printText(text)}<slot name="text" /></span>
    {/if}
    {#if $$slots.icon}
      <span class={c.icon}><slot name="icon" /></span>
    {/if}
    {#if (text || $$slots.text) && textPosition === 'after'}
      <span class={c.text}>{printText(text)}<slot name="text" /></span>
    {/if}
    <slot />
  </svelte:element>
{:else}
  <svelte:component
    this={component}
    class={text ? c.base.withText : c.base.iconOnly}
    {href}
    bind:this={rippleEl.current}
    on:click={onClick}
    {...$$restProps}
  >
    {#if (text || $$slots.text) && textPosition === 'before'}
      <span class={c.text}>{printText(text)}<slot name="text" /></span>
    {/if}
    {#if $$slots.icon}
      <span class={c.icon}><slot name="icon" /></span>
    {/if}
    {#if (text || $$slots.text) && textPosition === 'after'}
      <span class={c.text}>{printText(text)}<slot name="text" /></span>
    {/if}
    <slot />
  </svelte:component>
{/if}

// react/cjs/components/Fab.js
"use strict";

exports.__esModule = true;
exports.default = void 0;
var _react = _interopRequireWildcard(require("react"));
var _useTheme = require("../shared/use-theme.js");
var _useThemeClasses = require("../shared/use-theme-classes.js");
var _useTouchRipple = require("../shared/use-touch-ripple.js");
var _useDarkClasses = require("../shared/use-dark-classes.js");
var _FabClasses = require("../../../shared/cjs/classes/FabClasses.js");
var _FabColors = require("../../../shared/cjs/colors/FabColors.js");
function _getRequireWildcardCache(e) { if ("function" != typeof WeakMap) return null; var r = new WeakMap(), t = new WeakMap(); return (_getRequireWildcardCache = function (e) { return e ? t : r; })(e); }
function _interopRequireWildcard(e, r) { if (!r && e && e.__esModule) return e; if (null === e || "object" != typeof e && "function" != typeof e) return { default: e }; var t = _getRequireWildcardCache(r); if (t && t.has(e)) return t.get(e); var n = { __proto__: null }, a = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var u in e) if ("default" !== u && {}.hasOwnProperty.call(e, u)) { var i = a ? Object.getOwnPropertyDescriptor(e, u) : null; i && (i.get || i.set) ? Object.defineProperty(n, u, i) : n[u] = e[u]; } return n.default = e, t && t.set(e, n), n; }
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const Fab = /*#__PURE__*/(0, _react.forwardRef)((props, ref) => {
  const {
    component = 'a',
    className,
    colors: colorsProp,
    href,
    text,
    textPosition = 'after',
    icon,
    ios,
    material,
    touchRipple = true,
    // Children
    children,
    // Rest
    ...rest
  } = props;
  const rippleElRef = (0, _react.useRef)(null);
  (0, _react.useImperativeHandle)(ref, () => ({
    el: rippleElRef.current
  }));
  const Component = component;
  const attrs = {
    ...rest
  };
  const theme = (0, _useTheme.useTheme)({
    ios,
    material
  });
  const themeClasses = (0, _useThemeClasses.useThemeClasses)({
    ios,
    material
  });
  const dark = (0, _useDarkClasses.useDarkClasses)();
  (0, _useTouchRipple.useTouchRipple)(rippleElRef, theme === 'material' && touchRipple);
  const colors = (0, _FabColors.FabColors)(colorsProp, dark);
  const c = themeClasses((0, _FabClasses.FabClasses)(props, colors), className);
  return /*#__PURE__*/_react.default.createElement(Component, _extends({
    className: text ? c.base.withText : c.base.iconOnly,
    href: href,
    ref: rippleElRef,
    role: "button",
    tabIndex: "0"
  }, attrs), text && textPosition === 'before' && /*#__PURE__*/_react.default.createElement("span", {
    className: c.text
  }, text), icon && /*#__PURE__*/_react.default.createElement("span", {
    className: c.icon
  }, icon), text && textPosition === 'after' && /*#__PURE__*/_react.default.createElement("span", {
    className: c.text
  }, text), children);
});
Fab.displayName = 'Fab';
var _default = exports.default = Fab;
