// svelte/components/Message.svelte
<script>
  import { MessageClasses } from '../../shared/esm/classes/MessageClasses.js';
  import { MessageColors } from '../../shared/esm/colors/MessageColors.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { printText } from '../shared/print-text.js';
  import { cls } from '../../shared/esm/cls.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let component = 'div';
  export let id = undefined;
  export let text = '';
  export let name = undefined;
  export let type = 'sent';
  export let header = '';
  export let footer = '';
  export let textHeader = '';
  export let textFooter = '';
  export let avatar = undefined;

  export let onClick = undefined;

  const rippleEl = { current: null };

  const dark = useDarkClasses();

  $: colors = MessageColors(colorsProp, dark);

  $: c = useThemeClasses(
    { ios, material },
    MessageClasses({ type }, colors),
    className,
    (v) => (c = v)
  );

  $: classes = cls(
    c.message,

    type === 'sent' && c.messageSent,

    type === 'received' && c.messageReceived,

    className
  );
</script>

<svelte:element
  this={component}
  {id}
  bind:this={rippleEl.current}
  class={classes}
  on:click={onClick}
  {...$$restProps}
>
  {#if avatar || $$slots.avatar}
    <div class={c.messageAvatar}>{printText(avatar)}<slot name="avatar" /></div>
  {/if}
  <div class={c.messageContent}>
    {#if name || $$slots.name}
      <div class={c.messageName}>{printText(name)}<slot name="name" /></div>
    {/if}
    {#if header || $$slots.header}
      <div class={c.messageHeader}>
        {printText(header)}<slot name="header" />
      </div>
    {/if}
    <div class={c.messageBubble}>
      {#if textHeader || $$slots.textHeader}
        <div class={c.messageTextHeader}>
          {printText(textHeader)}<slot name="textHeader" />
        </div>
      {/if}
      {#if text || $$slots.text}
        <div class={c.messageText}>{printText(text)}<slot name="text" /></div>
      {/if}
      {#if textFooter || $$slots.textFooter}
        <div class={c.messageTextFooter}>
          {printText(textFooter)}<slot name="textFooter" />
        </div>
      {/if}
    </div>
    {#if footer || $$slots.footer}
      <div class={c.messageFooter}>
        {printText(footer)}<slot name="footer" />
      </div>
    {/if}
  </div>
</svelte:element>

// react/cjs/components/Message.js
"use strict";

exports.__esModule = true;
exports.default = void 0;
var _react = _interopRequireWildcard(require("react"));
var _useThemeClasses = require("../shared/use-theme-classes.js");
var _cls = require("../../../shared/cjs/cls.js");
var _useDarkClasses = require("../shared/use-dark-classes.js");
var _MessageClasses = require("../../../shared/cjs/classes/MessageClasses.js");
var _MessageColors = require("../../../shared/cjs/colors/MessageColors.js");
function _getRequireWildcardCache(e) { if ("function" != typeof WeakMap) return null; var r = new WeakMap(), t = new WeakMap(); return (_getRequireWildcardCache = function (e) { return e ? t : r; })(e); }
function _interopRequireWildcard(e, r) { if (!r && e && e.__esModule) return e; if (null === e || "object" != typeof e && "function" != typeof e) return { default: e }; var t = _getRequireWildcardCache(r); if (t && t.has(e)) return t.get(e); var n = { __proto__: null }, a = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var u in e) if ("default" !== u && {}.hasOwnProperty.call(e, u)) { var i = a ? Object.getOwnPropertyDescriptor(e, u) : null; i && (i.get || i.set) ? Object.defineProperty(n, u, i) : n[u] = e[u]; } return n.default = e, t && t.set(e, n), n; }
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); } /* eslint-disable jsx-a11y/alt-text */ // import { useTheme } from '../shared/use-theme.js';
const Message = /*#__PURE__*/(0, _react.forwardRef)((props, ref) => {
  const {
    component = 'div',
    className,
    colors: colorsProp,
    id,
    text,
    name,
    type = 'sent',
    header,
    footer,
    textHeader,
    textFooter,
    avatar,
    ios,
    material,
    children,
    ...rest
  } = props;
  const elRef = (0, _react.useRef)(null);
  (0, _react.useImperativeHandle)(ref, () => ({
    el: elRef.current
  }));
  // const theme = useTheme({ ios, material });
  const themeClasses = (0, _useThemeClasses.useThemeClasses)({
    ios,
    material
  });
  const dark = (0, _useDarkClasses.useDarkClasses)();
  const colors = (0, _MessageColors.MessageColors)(colorsProp, dark);
  const c = themeClasses((0, _MessageClasses.MessageClasses)({
    ...props
  }, colors));
  const Component = component;
  const attrs = {
    ...rest
  };
  const classes = (0, _cls.cls)(className, c.message, {
    [c.messageSent]: type === 'sent',
    [c.messageReceived]: type === 'received'
  });
  return /*#__PURE__*/_react.default.createElement(Component, _extends({
    id: id,
    ref: elRef,
    className: classes
  }, attrs), avatar && /*#__PURE__*/_react.default.createElement("div", {
    className: c.messageAvatar
  }, avatar), /*#__PURE__*/_react.default.createElement("div", {
    className: c.messageContent
  }, name && /*#__PURE__*/_react.default.createElement("div", {
    className: c.messageName
  }, name), header && /*#__PURE__*/_react.default.createElement("div", {
    className: c.messageHeader
  }, header), /*#__PURE__*/_react.default.createElement("div", {
    className: c.messageBubble
  }, textHeader && /*#__PURE__*/_react.default.createElement("div", {
    className: c.messageTextHeader
  }, textHeader), text && /*#__PURE__*/_react.default.createElement("div", {
    className: c.messageText
  }, text), textFooter && /*#__PURE__*/_react.default.createElement("div", {
    className: c.messageTextFooter
  }, textFooter)), footer && /*#__PURE__*/_react.default.createElement("div", {
    className: c.messageFooter
  }, footer)));
});
Message.displayName = 'Message';
var _default = exports.default = Message;
