// vue/components/Breadcrumbs.vue
<template>
  <component :is="component" :class="c.base">
    <slot />
  </component>
</template>
<script>
  import { useContext } from '../shared/use-context.js';
  import { BreadcrumbsClasses } from '../../shared/esm/classes/BreadcrumbsClasses.js';

  import { themeClasses } from '../shared/use-theme-classes.js';

  export default {
    name: 'k-breadcrumbs',
    props: {
      component: {
        type: String,
        default: 'span',
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      fontSizeIos: {
        type: String,
        default: 'text-[17px]',
      },
      fontSizeMaterial: {
        type: String,
        default: 'text-[16px]',
      },
    },
    setup(props) {
      const context = useContext();
      const useThemeClasses = themeClasses(context);
      const c = useThemeClasses(props, () => BreadcrumbsClasses(props));
      return {
        c,
      };
    },
  };
</script>

// react/esm/components/Breadcrumbs.js
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
import React, { useRef, forwardRef, useImperativeHandle } from 'react';
import { BreadcrumbsClasses } from '../../../shared/esm/classes/BreadcrumbsClasses.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';
const Breadcrumbs = /*#__PURE__*/forwardRef((props, ref) => {
  const {
    component = 'div',
    className,
    fontSizeIos = 'text-[17px]',
    fontSizeMaterial = 'text-[14px]',
    ios,
    material,
    // Children
    children,
    // Rest
    ...rest
  } = props;
  const elRef = useRef(null);
  useImperativeHandle(ref, () => ({
    el: elRef.current
  }));
  const Component = component;
  const attrs = {
    ...rest
  };
  const themeClasses = useThemeClasses({
    ios,
    material
  });
  const c = themeClasses(BreadcrumbsClasses({
    ...props,
    fontSizeIos,
    fontSizeMaterial
  }), className);
  return /*#__PURE__*/React.createElement(Component, _extends({
    ref: elRef,
    className: c.base
  }, attrs), children);
});
Breadcrumbs.displayName = 'Breadcrumbs';
export default Breadcrumbs;
