// svelte/components/Button.svelte
<script>
  import { cls } from '../../shared/esm/cls.js';
  import { useTouchRipple } from '../shared/use-touch-ripple.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useTheme } from '../shared/use-theme.js';

  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { ButtonClasses } from '../../shared/esm/classes/ButtonClasses.js';
  import { ButtonColors } from '../../shared/esm/colors/ButtonColors.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let component = 'button'; // or 'a'

  // Anchor props
  export let href = undefined;

  export let disabled = false;

  // Style props
  export let outline = undefined;
  export let outlineIos = undefined;
  export let outlineMaterial = undefined;
  export let clear = undefined;
  export let clearIos = undefined;
  export let clearMaterial = undefined;
  export let tonal = undefined;
  export let tonalIos = undefined;
  export let tonalMaterial = undefined;
  export let rounded = undefined;
  export let roundedIos = undefined;
  export let roundedMaterial = undefined;
  export let small = undefined;
  export let smallIos = undefined;
  export let smallMaterial = undefined;
  export let large = undefined;
  export let largeIos = undefined;
  export let largeMaterial = undefined;
  export let raised = undefined;
  export let raisedIos = undefined;
  export let raisedMaterial = undefined;

  export let inline = false;

  // Segmented
  export let segmented = false;
  export let segmentedStrong = false;
  export let segmentedActive = false;

  export let touchRipple = true;

  export let onClick = undefined;

  let theme;
  theme = useTheme({}, (v) => (theme = v));

  const rippleEl = { current: null };

  $: attrs = {
    href,
    ...$$restProps,
  };

  const dark = useDarkClasses();

  $: useTouchRipple(rippleEl, touchRipple);

  $: isOutline =
    typeof outline === 'undefined'
      ? theme === 'ios'
        ? outlineIos
        : outlineMaterial
      : outline;
  $: isClear =
    typeof clear === 'undefined'
      ? theme === 'ios'
        ? clearIos
        : clearMaterial
      : clear;
  $: isTonal =
    typeof tonal === 'undefined'
      ? theme === 'ios'
        ? tonalIos
        : tonalMaterial
      : tonal;
  $: isRounded =
    typeof rounded === 'undefined'
      ? theme === 'ios'
        ? roundedIos
        : roundedMaterial
      : rounded;
  $: isSmall =
    typeof small === 'undefined'
      ? theme === 'ios'
        ? smallIos
        : smallMaterial
      : small;
  $: isLarge =
    typeof large === 'undefined'
      ? theme === 'ios'
        ? largeIos
        : largeMaterial
      : large;
  $: isRaised =
    typeof raised === 'undefined'
      ? theme === 'ios'
        ? raisedIos
        : raisedMaterial
      : raised;

  $: size = isLarge ? 'large' : isSmall ? 'small' : 'medium';

  const getStyle = (
    isOutline,
    isClear,
    isTonal,
    segmented,
    segmentedActive,
    segmentedStrong
  ) => {
    let s = isOutline
      ? 'outline'
      : isClear || (segmented && !segmentedActive)
      ? 'clear'
      : isTonal
      ? 'tonal'
      : 'fill';
    if (segmentedStrong) s = 'segmentedStrong';
    if (segmentedStrong && segmentedActive) s = 'segmentedStrongActive';
    return s;
  };

  $: style = getStyle(
    isOutline,
    isClear,
    isTonal,
    segmented,
    segmentedActive,
    segmentedStrong
  );

  $: colors = ButtonColors(colorsProp, dark);

  $: c = useThemeClasses(
    { ios, material },
    ButtonClasses(
      {
        inline,
        segmented,
        segmentedStrong,
        segmentedActive,
        disabled,
        outline: isOutline,
        clear: isClear,
        tonal: isTonal,
        rounded: isRounded,
        small: isSmall,
        large: isLarge,
        raised: isRaised,
      },
      colors,
      className,
      dark
    ),
    '',
    (v) => (c = v)
  );

  $: classes = cls(
    c.base[isRounded ? 'rounded' : 'square'],

    // style
    c.style[style],

    // size
    c.size[size],

    isRaised && c.raised,

    className
  );

  const Component = component === 'button' && href ? 'a' : component;
</script>

{#if typeof component === 'string'}
  <svelte:element
    this={Component}
    bind:this={rippleEl.current}
    class={classes}
    {disabled}
    {...attrs}
    role="button"
    tabindex="0"
    on:click={onClick}
  >
    <slot />
  </svelte:element>
{:else}
  <svelte:component
    this={component}
    bind:this={rippleEl.current}
    class={classes}
    {disabled}
    {...attrs}
    on:click={onClick}
  >
    <slot />
  </svelte:component>
{/if}

// react/esm/components/Button.js
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
import React, { useRef, forwardRef, useImperativeHandle } from 'react';
import { cls } from '../../../shared/esm/cls.js';
import { useTheme } from '../shared/use-theme.js';
import { useTouchRipple } from '../shared/use-touch-ripple.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import { ButtonClasses } from '../../../shared/esm/classes/ButtonClasses.js';
import { ButtonColors } from '../../../shared/esm/colors/ButtonColors.js';
const Button = /*#__PURE__*/forwardRef((props, ref) => {
  const {
    component = 'button',
    className,
    colors: colorsProp,
    ios,
    material,
    disabled,
    // Anchor props
    href,
    // Style props
    outline,
    outlineIos,
    outlineMaterial,
    clear,
    clearIos,
    clearMaterial,
    tonal,
    tonalIos,
    tonalMaterial,
    rounded,
    roundedIos,
    roundedMaterial,
    small,
    smallIos,
    smallMaterial,
    large,
    largeIos,
    largeMaterial,
    raised,
    raisedIos,
    raisedMaterial,
    inline,
    // Segmented
    segmented,
    segmentedStrong,
    segmentedActive,
    touchRipple = true,
    // Children
    children,
    // Rest
    ...rest
  } = props;
  const rippleElRef = useRef(null);
  useImperativeHandle(ref, () => ({
    el: rippleElRef.current
  }));
  let Component = component;
  if (typeof props.component === 'undefined' && (href || href === '')) Component = 'a';
  const attrs = {
    href,
    ...rest
  };
  const theme = useTheme({
    ios,
    material
  });
  const themeClasses = useThemeClasses({
    ios,
    material
  });
  const dark = useDarkClasses();
  useTouchRipple(rippleElRef, theme === 'material' && touchRipple);
  const getThemeSpecificProps = obj => {
    const res = {};
    Object.keys(obj).forEach(key => {
      res[key] = typeof obj[key] === 'undefined' ? theme === 'ios' ? props[`${key}Ios`] : props[`${key}Material`] : obj[key];
    });
    return res;
  };
  const themeProps = getThemeSpecificProps({
    outline,
    clear,
    tonal,
    rounded,
    small,
    large,
    raised
  });
  const size = themeProps.large ? 'large' : themeProps.small ? 'small' : 'medium';
  let style = themeProps.outline ? 'outline' : themeProps.clear || segmented && !segmentedActive ? 'clear' : themeProps.tonal ? 'tonal' : 'fill';
  if (segmentedStrong) style = 'segmentedStrong';
  if (segmentedStrong && segmentedActive) style = 'segmentedStrongActive';
  const colors = ButtonColors(colorsProp, dark);
  const c = themeClasses(ButtonClasses({
    ...props,
    ...themeProps
  }, colors, className, dark));
  const classes = cls(c.base[themeProps.rounded ? 'rounded' : 'square'],
  // style
  c.style[style],
  // size
  c.size[size], themeProps.raised && c.raised, className);
  return /*#__PURE__*/React.createElement(Component, _extends({
    ref: rippleElRef,
    className: classes,
    disabled: disabled,
    role: "button",
    tabIndex: "0"
  }, attrs), children);
});
Button.displayName = 'Button';
export default Button;
