// vue/components/ActionsButton.vue
<template>
  <component
    :is="Component"
    ref="rippleElRef"
    role="button"
    tabindex="0"
    :class="c.base"
  >
    <slot />
  </component>
</template>
<script>
  import { ref, computed } from 'vue';
  import { useContext } from '../shared/use-context.js';

  import { useTouchRipple } from '../shared/use-touch-ripple.js';
  import { themeClasses } from '../shared/use-theme-classes.js';
  import { useTheme } from '../shared/use-theme.js';
  import { darkClasses } from '../shared/use-dark-classes.js';
  import { ActionsButtonClasses } from '../../shared/esm/classes/ActionsButtonClasses.js';
  import { ActionsButtonColors } from '../../shared/esm/colors/ActionsButtonColors.js';

  export default {
    name: 'k-actions-button',
    props: {
      component: {
        type: String,
        default: 'button',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      // Anchor props
      href: {
        type: [Boolean, String],
        default: undefined,
      },
      touchRipple: {
        type: Boolean,
        default: true,
      },
      dividers: { type: Boolean, default: undefined },
      bold: { type: Boolean, default: undefined },
      boldIos: { type: Boolean, default: false },
      boldMaterial: { type: Boolean, default: false },
      fontSizeIos: { type: String, default: 'text-xl' },
      fontSizeMaterial: { type: String, default: 'text-base' },
    },
    setup(props) {
      const context = useContext();
      const useDarkClasses = darkClasses(context);
      const useThemeClasses = themeClasses(context);
      const rippleElRef = ref(null);
      const Component = computed(() => {
        let c = props.component;
        if (
          typeof props.component === 'undefined' &&
          (props.href || props.href === '')
        ) {
          c = 'a';
        }
        return c;
      });

      useTouchRipple(rippleElRef, props, { context });

      const colors = computed(() =>
        ActionsButtonColors(props.colors || {}, useDarkClasses)
      );

      const theme = useTheme({}, context);

      const isDividers = computed(() =>
        typeof props.dividers === 'undefined'
          ? theme.value === 'ios'
          : props.dividers
      );

      const isBold = computed(() =>
        typeof props.bold === 'undefined'
          ? theme.value === 'ios'
            ? props.boldIos
            : props.boldMaterial
          : props.bold
      );

      const c = useThemeClasses(props, () =>
        ActionsButtonClasses(
          { ...props, bold: isBold.value, dividers: isDividers.value },
          colors.value,
          useDarkClasses
        )
      );

      return {
        c,
        Component,
        rippleElRef,
      };
    },
  };
</script>

// svelte/components/ActionsButton.svelte
<script>
  import { ActionsButtonClasses } from '../../shared/esm/classes/ActionsButtonClasses.js';
  import { ActionsButtonColors } from '../../shared/esm/colors/ActionsButtonColors.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useTheme } from '../shared/use-theme.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useTouchRipple } from '../shared/use-touch-ripple.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let component = 'button';
  export let href = undefined;

  export let bold = undefined;
  export let boldIos = false;
  export let boldMaterial = false;
  export let fontSizeIos = 'text-xl';
  export let fontSizeMaterial = 'text-base';
  export let touchRipple = true;
  export let dividers = true;

  export let onClick = undefined;

  const rippleEl = { current: null };

  const dark = useDarkClasses();

  $: useTouchRipple(rippleEl, touchRipple);

  $: attrs = {
    href,
    ...$$restProps,
  };

  let Component = component;
  if (typeof component === 'undefined' && (href || href === '')) {
    Component = 'a';
  } else if (typeof component === 'undefined') {
    Component = 'button';
  }

  $: colors = ActionsButtonColors(colorsProp, dark);

  let theme;
  theme = useTheme({}, (v) => (theme = v));

  $: isDividers = typeof dividers === 'undefined' ? theme === 'ios' : dividers;

  $: isBold =
    typeof bold === 'undefined'
      ? theme === 'ios'
        ? boldIos
        : boldMaterial
      : bold;

  $: c = useThemeClasses(
    { ios, material },
    ActionsButtonClasses(
      { bold: isBold, fontSizeIos, fontSizeMaterial, dividers: isDividers },
      colors,
      dark
    ),
    className,
    (v) => (c = v)
  );
</script>

<svelte:element
  this={Component}
  bind:this={rippleEl.current}
  class={c.base}
  role="button"
  tabindex="0"
  on:click={onClick}
  {...attrs}
>
  <slot />
</svelte:element>
