// vue/components/Breadcrumbs.vue
<template>
  <component :is="component" :class="c.base">
    <slot />
  </component>
</template>
<script>
  import { useContext } from '../shared/use-context.js';
  import { BreadcrumbsClasses } from '../../shared/esm/classes/BreadcrumbsClasses.js';

  import { themeClasses } from '../shared/use-theme-classes.js';

  export default {
    name: 'k-breadcrumbs',
    props: {
      component: {
        type: String,
        default: 'span',
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      fontSizeIos: {
        type: String,
        default: 'text-[17px]',
      },
      fontSizeMaterial: {
        type: String,
        default: 'text-[16px]',
      },
    },
    setup(props) {
      const context = useContext();
      const useThemeClasses = themeClasses(context);
      const c = useThemeClasses(props, () => BreadcrumbsClasses(props));
      return {
        c,
      };
    },
  };
</script>

// svelte/components/Breadcrumbs.svelte
<script>
  import { BreadcrumbsClasses } from '../../shared/esm/classes/BreadcrumbsClasses.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  let className = undefined;
  export { className as class };
  export let ios = undefined;
  export let material = undefined;

  export let fontSizeIos = 'text-[17px]';
  export let fontSizeMaterial = 'text-[14px]';

  $: c = useThemeClasses(
    { ios, material },
    BreadcrumbsClasses({ fontSizeIos, fontSizeMaterial }),
    className,
    (v) => (c = v)
  );
</script>

<div class={c.base} {...$$restProps}>
  <slot />
</div>
