// react/esm/components/Card.js
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
import React, { useRef, forwardRef, useImperativeHandle } from 'react';
import { CardClasses } from '../../../shared/esm/classes/CardClasses.js';
import { CardColors } from '../../../shared/esm/colors/CardColors.js';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { useTheme } from '../shared/use-theme.js';
const Card = /*#__PURE__*/forwardRef((props, ref) => {
  const {
    component = 'div',
    className,
    margin = 'm-4',
    colors: colorsProp,
    header,
    footer,
    ios,
    material,
    headerFontSizeIos = 'text-[17px]',
    headerFontSizeMaterial = 'text-[22px]',
    contentWrap = true,
    contentWrapPadding = 'p-4',
    // Style
    raised,
    raisedIos,
    raisedMaterial,
    outline,
    outlineIos,
    outlineMaterial,
    headerDivider = false,
    footerDivider = false,
    // Children
    children,
    // Rest
    ...rest
  } = props;
  const elRef = useRef(null);
  useImperativeHandle(ref, () => ({
    el: elRef.current
  }));
  const Component = component;
  const attrs = {
    ...rest
  };
  const theme = useTheme();
  const themeClasses = useThemeClasses({
    ios,
    material
  });
  const dark = useDarkClasses();
  const colors = CardColors(colorsProp, dark);
  const isOutline = typeof outline === 'undefined' ? theme === 'ios' ? outlineIos : outlineMaterial : outline;
  const isRaised = typeof raised === 'undefined' ? theme === 'ios' ? raisedIos : raisedMaterial : raised;
  const style = isOutline ? 'outline' : isRaised ? 'raised' : 'plain';
  const c = themeClasses(CardClasses({
    ...props,
    margin,
    contentWrapPadding,
    headerDivider,
    footerDivider,
    headerFontSizeIos,
    headerFontSizeMaterial,
    outline: isOutline,
    raised: isRaised
  }, colors, dark), className);
  return /*#__PURE__*/React.createElement(Component, _extends({
    ref: elRef,
    className: c.base[style]
  }, attrs), header && /*#__PURE__*/React.createElement("div", {
    className: c.header
  }, header), contentWrap ? /*#__PURE__*/React.createElement("div", {
    className: c.content
  }, children) : children, footer && /*#__PURE__*/React.createElement("div", {
    className: c.footer
  }, footer));
});
Card.displayName = 'Card';
export default Card;

// svelte/components/Card.svelte
<script>
  import { CardClasses } from '../../shared/esm/classes/CardClasses.js';
  import { CardColors } from '../../shared/esm/colors/CardColors.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useTheme } from '../shared/use-theme.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { printText } from '../shared/print-text.js';

  export let component = 'div';
  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let margin = 'm-4';
  export let header = '';
  export let footer = '';
  export let contentWrap = true;
  export let contentWrapPadding = 'p-4';
  export let raised = undefined;
  export let raisedIos = undefined;
  export let raisedMaterial = undefined;
  export let outline = undefined;
  export let outlineIos = undefined;
  export let outlineMaterial = undefined;
  export let headerDivider = false;
  export let footerDivider = false;

  const dark = useDarkClasses();

  let theme;
  theme = useTheme({}, (v) => (theme = v));

  $: isOutline =
    typeof outline === 'undefined'
      ? theme === 'ios'
        ? outlineIos
        : outlineMaterial
      : outline;

  $: isRaised =
    typeof raised === 'undefined'
      ? theme === 'ios'
        ? raisedIos
        : raisedMaterial
      : raised;

  $: colors = CardColors(colorsProp, dark);

  $: style = isOutline ? 'outline' : isRaised ? 'raised' : 'plain';

  $: c = useThemeClasses(
    { ios, material },
    CardClasses(
      {
        margin,
        outline: isOutline,
        raised: isRaised,
        contentWrapPadding,
        headerDivider,
        footerDivider,
      },
      colors,
      dark
    ),
    className,
    (v) => (c = v)
  );
</script>

{#if typeof component === 'string'}
  <svelte:element this={component} class={c.base[style]} {...$$restProps}>
    {#if header || $$slots.header}
      <div class={c.header}>{printText(header)}<slot name="header" /></div>
    {/if}
    {#if contentWrap}
      <div class={c.content}><slot /></div>
    {:else}
      <slot />
    {/if}
    {#if footer || $$slots.footer}
      <div class={c.footer}>{printText(footer)}<slot name="footer" /></div>
    {/if}
  </svelte:element>
{:else}
  <svelte:component this={component} class={c.base[style]} {...$$restProps}>
    {#if header || $$slots.header}
      <div class={c.header}>{printText(header)}<slot name="header" /></div>
    {/if}
    {#if contentWrap}
      <div class={c.content}><slot /></div>
    {:else}
      <slot />
    {/if}
    {#if footer || $$slots.footer}
      <div class={c.footer}>{printText(footer)}<slot name="footer" /></div>
    {/if}
  </svelte:component>
{/if}
