// vue/components/Chip.vue
<template>
  <component :is="component" :class="c.base[style]">
    <div v-if="slots.media" :class="c.media"><slot name="media" /></div>
    <slot />
    <div
      v-if="deleteButton"
      :class="c.deleteButton"
      role="button"
      tabindex="0"
      @click="onDelete"
    >
      <delete-icon :theme="theme" class="h-4 w-4" />
    </div>
  </component>
</template>
<script>
  import { computed } from 'vue';
  import { useContext } from '../shared/use-context.js';

  import { ChipClasses } from '../../shared/esm/classes/ChipClasses.js';

  import { ChipColors } from '../../shared/esm/colors/ChipColors.js';

  import { darkClasses } from '../shared/use-dark-classes.js';

  import { useTheme } from '../shared/use-theme.js';

  import { themeClasses } from '../shared/use-theme-classes.js';
  import DeleteIcon from './icons/DeleteIcon.vue';

  export default {
    name: 'k-chip',
    components: {
      DeleteIcon,
    },
    props: {
      component: {
        type: String,
        default: 'div',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      deleteButton: {
        type: Boolean,
        default: false,
      },
      outline: {
        type: Boolean,
        default: false,
      },
    },
    emits: ['delete'],
    setup(props, ctx) {
      const context = useContext();
      const useDarkClasses = darkClasses(context);
      const useThemeClasses = themeClasses(context);
      const style = computed(() => (props.outline ? 'outline' : 'fill'));
      const theme = useTheme({}, context);

      const colors = computed(() =>
        ChipColors(props.colors || {}, useDarkClasses)
      );

      const c = useThemeClasses(props, () => ChipClasses(props, colors.value));

      const onDelete = () => {
        ctx.emit('delete');
      };
      return {
        c,
        slots: ctx.slots,
        style,
        theme,
        onDelete,
      };
    },
  };
</script>

// svelte/components/Chip.svelte
<script>
  import { ChipClasses } from '../../shared/esm/classes/ChipClasses.js';
  import { ChipColors } from '../../shared/esm/colors/ChipColors.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useTheme } from '../shared/use-theme.js';

  import DeleteIcon from './icons/DeleteIcon.svelte';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let deleteButton = undefined;
  export let onDelete = undefined;
  export let outline = false;

  export let onClick = undefined;

  const dark = useDarkClasses();
  let theme;
  theme = useTheme({}, (v) => (theme = v));

  $: style = outline ? 'outline' : 'fill';

  $: colors = ChipColors(colorsProp, dark);

  $: c = useThemeClasses(
    { ios, material },
    ChipClasses({}, colors),
    className,
    (v) => (c = v)
  );
</script>

<div class={c.base[style]} {...$$restProps} on:click={onClick}>
  {#if $$slots.media}
    <div class={c.media}><slot name="media" /></div>
  {/if}
  <slot />
  {#if deleteButton}
    <div class={c.deleteButton} role="button" tabindex="0" on:click={onDelete}>
      <DeleteIcon {theme} class="h-4 w-4" />
    </div>
  {/if}
</div>
