// react/esm/components/ListInput.js
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
import React, { useRef, useState, forwardRef, useImperativeHandle } from 'react';
import { cls } from '../../../shared/esm/cls.js';
import { useTheme } from '../shared/use-theme.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import DeleteIcon from './icons/DeleteIcon.js';
import DropdownIcon from './icons/DropdownIcon.js';
import ListItem from './ListItem.js';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import { ListInputClasses } from '../../../shared/esm/classes/ListInputClasses.js';
import { ListInputColors } from '../../../shared/esm/colors/ListInputColors.js';
const ListInput = /*#__PURE__*/forwardRef((props, ref) => {
  const {
    component = 'li',
    className,
    colors: colorsProp,
    label,
    floatingLabel,
    outline,
    outlineIos,
    outlineMaterial,
    media,
    input,
    // for custom input
    info,
    // string
    error,
    // string or bool
    clearButton,
    dropdown,
    // input props
    inputId,
    inputStyle,
    inputClassName = '',
    name,
    value,
    defaultValue,
    type = 'text',
    inputMode,
    readOnly,
    required,
    disabled,
    placeholder,
    size,
    accept,
    autoComplete,
    autoCorrect,
    autoCapitalize,
    spellCheck,
    autoFocus,
    autoSave,
    max,
    min,
    step,
    maxLength,
    minLength,
    multiple,
    pattern,
    tabIndex,
    onInput,
    onChange,
    onFocus,
    onBlur,
    onClear,
    ios,
    material,
    children,
    ...rest
  } = props;
  const inputElRef = useRef(null);
  const elRef = useRef(null);
  useImperativeHandle(ref, () => ({
    el: elRef.current,
    inputEl: inputElRef.current
  }));
  const [isFocused, setIsFocused] = useState(false);
  const theme = useTheme({
    ios,
    material
  });
  const themeClasses = useThemeClasses({
    ios,
    material
  });
  const dark = useDarkClasses();
  const colors = ListInputColors(colorsProp, dark);
  const labelStyle = label && floatingLabel ? 'floating' : 'stacked';
  const labelStyleIsFloating = labelStyle === 'floating' ? 'floating' : 'notFloating';
  const getDomValue = () => {
    if (!inputElRef.current) return undefined;
    return inputElRef.current.value;
  };
  const isInputHasValue = () => {
    const domValue = getDomValue();
    return typeof value === 'undefined' ? domValue || domValue === 0 : value || value === 0;
  };
  const isFloatingTransformed = label && floatingLabel && !isInputHasValue() && !isFocused;
  const getLabelColor = () => {
    if (error) return colors.errorText;
    if (theme === 'material') {
      return isFocused ? colors.labelTextFocusMaterial : colors.labelTextMaterial;
    }
    if (theme === 'ios') {
      return isFocused ? colors.labelTextFocusIos : colors.labelTextIos;
    }
    return '';
  };
  const onFocusInternal = e => {
    setIsFocused(true);
    if (onFocus) onFocus(e);
  };
  const onBlurInternal = e => {
    setIsFocused(false);
    if (onBlur) onBlur(e);
  };
  const isOutline = typeof outline === 'undefined' ? theme === 'ios' ? outlineIos : outlineMaterial : outline;
  const c = themeClasses(ListInputClasses({
    ...props,
    outline: isOutline
  }, colors, {
    isFloatingTransformed,
    isFocused,
    darkClasses: dark,
    getLabelColor,
    inputClassName,
    hasLabel: !!label
  }));
  const attrs = {
    ...rest
  };
  const createInput = () => {
    if (input) return input;
    const InputComponent = type === 'select' || type === 'textarea' ? type : 'input';
    const needsType = InputComponent === 'input';
    return /*#__PURE__*/React.createElement(InputComponent, {
      id: inputId,
      ref: inputElRef,
      className: c.input[labelStyleIsFloating],
      style: inputStyle,
      name: name,
      type: needsType ? type : undefined,
      placeholder: placeholder,
      inputMode: inputMode,
      size: size,
      accept: accept,
      autoComplete: autoComplete,
      autoCorrect: autoCorrect,
      autoCapitalize: autoCapitalize,
      spellCheck: spellCheck,
      autoFocus: autoFocus,
      autoSave: autoSave,
      disabled: disabled,
      max: max,
      maxLength: maxLength,
      min: min,
      minLength: minLength,
      step: step,
      multiple: multiple,
      readOnly: readOnly,
      required: required,
      pattern: pattern,
      tabIndex: tabIndex,
      value: value,
      defaultValue: defaultValue,
      onInput: onInput,
      onChange: onChange,
      onFocus: onFocusInternal,
      onBlur: onBlurInternal
    }, type === 'select' ? children : null);
  };
  const errorInfoContent = /*#__PURE__*/React.createElement(React.Fragment, null, error && error !== true && /*#__PURE__*/React.createElement("div", {
    className: cls(c.errorInfo, c.error)
  }, error), info && !error && /*#__PURE__*/React.createElement("div", {
    className: cls(c.errorInfo, c.info)
  }, info));
  const innerChildren = /*#__PURE__*/React.createElement(React.Fragment, null, label && /*#__PURE__*/React.createElement("div", {
    className: c.label[labelStyle]
  }, /*#__PURE__*/React.createElement("div", {
    className: c.labelText
  }, label)), /*#__PURE__*/React.createElement("div", {
    className: c.inputWrap[labelStyle]
  }, createInput(), clearButton && /*#__PURE__*/React.createElement(DeleteIcon, {
    theme: theme,
    onClick: onClear,
    className: c.clearButton
  }), dropdown && /*#__PURE__*/React.createElement(DropdownIcon, {
    className: c.dropdown
  })), errorInfoContent);
  return /*#__PURE__*/React.createElement(ListItem, _extends({
    ref: elRef,
    component: component,
    media: media,
    className: c.base,
    title: null,
    mediaClassName: c.media,
    innerClassName: c.inner[labelStyle],
    contentClassName: c.itemContent,
    titleWrapClassName: c.titleWrap,
    innerChildren: innerChildren,
    contentChildren: (isOutline || theme === 'material') && /*#__PURE__*/React.createElement("span", {
      className: c.border
    }),
    dividers: theme === 'material' || isOutline ? false : undefined
  }, attrs), type !== 'select' ? children : null);
});
ListInput.displayName = 'ListInput';
export default ListInput;

// svelte/components/ListInput.svelte
<script>
  import { useTheme } from '../shared/use-theme.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import DeleteIcon from './icons/DeleteIcon.svelte';
  import DropdownIcon from './icons/DropdownIcon.svelte';
  import ListItem from './ListItem.svelte';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { ListInputClasses } from '../../shared/esm/classes/ListInputClasses.js';
  import { ListInputColors } from '../../shared/esm/colors/ListInputColors.js';
  import { cls } from '../../shared/esm/cls.js';
  import { printText } from '../shared/print-text.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let component = 'li';

  export let label = '';
  export let outline = undefined;
  export let outlineIos = undefined;
  export let outlineMaterial = undefined;
  export let floatingLabel = false;
  export let info = undefined; // string
  export let error = undefined; // string or bool
  export let clearButton = false;
  export let dropdown = false;

  // input props
  export let inputId = undefined;
  export let inputStyle = undefined;
  export let inputClass = '';

  export let name = undefined;
  export let value = undefined;
  export let type = 'text';
  export let inputmode = undefined;
  export let readonly = undefined;
  export let required = undefined;
  export let disabled = undefined;
  export let placeholder = undefined;
  export let size = undefined;
  export let accept = undefined;
  export let autocomplete = undefined;
  export let autocorrect = undefined;
  export let autocapitalize = undefined;
  export let spellcheck = undefined;
  export let autofocus = undefined;
  export let autosave = undefined;
  export let max = undefined;
  export let min = undefined;
  export let step = undefined;
  export let maxlength = undefined;
  export let minlength = undefined;
  export let multiple = undefined;
  export let pattern = undefined;
  export let tabindex = undefined;

  export let onInput = undefined;
  export let onChange = undefined;
  export let onFocus = undefined;
  export let onBlur = undefined;
  export let onClear = undefined;

  let theme;
  theme = useTheme({ ios, material }, (v) => (theme = v));

  $: isOutline =
    typeof outline === 'undefined'
      ? theme === 'ios'
        ? outlineIos
        : outlineMaterial
      : outline;

  let inputEl = null;

  let isFocused = false;

  const dark = useDarkClasses();

  $: colors = ListInputColors(colorsProp, dark);

  $: labelStyle = label && floatingLabel ? 'floating' : 'stacked';
  $: labelStyleIsFloating =
    labelStyle === 'floating' ? 'floating' : 'notFloating';

  const getDomValue = () => {
    if (!inputEl) return undefined;
    return inputEl.value;
  };

  const isInputHasValue = () => {
    const domValue = getDomValue();
    return typeof value === 'undefined'
      ? domValue || domValue === 0
      : value || value === 0;
  };
  $: isFloatingTransformed =
    (label || $$slots.label) &&
    floatingLabel &&
    !isInputHasValue() &&
    !isFocused;

  const getLabelColor = () => {
    if (error || $$slots.error) return colors.errorText;
    if (theme === 'material') {
      return isFocused
        ? colors.labelTextFocusMaterial
        : colors.labelTextMaterial;
    }
    if (theme === 'ios') {
      return isFocused ? colors.labelTextFocusIos : colors.labelTextIos;
    }

    return '';
  };

  const onFocusInternal = (e) => {
    isFocused = true;
    if (onFocus) onFocus(e);
  };
  const onBlurInternal = (e) => {
    isFocused = false;
    if (onBlur) onBlur(e);
  };

  $: c = useThemeClasses(
    { ios, material },
    ListInputClasses(
      {
        error,
        type,
        inputClass,
        outline: isOutline,
      },
      colors,
      {
        isFloatingTransformed,
        isFocused,
        darkClasses: dark,
        getLabelColor,
        inputClass,
        hasLabel: !!label || $$slots.label,
      }
    ),
    className,
    (v) => (c = v)
  );

  $: InputComponent = type === 'select' || type === 'textarea' ? type : 'input';
  $: needsType = InputComponent === 'input';
</script>

<ListItem
  {component}
  class={c.base}
  title={undefined}
  mediaClass={c.media}
  innerClass={c.inner[labelStyle]}
  contentClass={c.itemContent}
  titleWrapClass={c.titleWrap}
  withMedia={!!$$slots.media}
  withTitle={!!$$slots.label || !!label}
  dividers={theme === 'material' || isOutline ? false : undefined}
  {...$$restProps}
>
  <svelte:fragment slot="content">
    {#if isOutline || theme === 'material'}
      <span class={c.border} />
    {/if}
  </svelte:fragment>
  <svelte:fragment slot="media">
    {#if $$slots.media}
      <slot name="media" />
    {/if}
  </svelte:fragment>

  <svelte:fragment slot="inner">
    {#if label || $$slots.label}
      <div class={c.label[labelStyle]}>
        <div class={c.labelText}>
          {printText(label)}
          <slot name="label" />
        </div>
      </div>
    {/if}
    <div class={c.inputWrap[labelStyle]}>
      {#if $$slots.input}
        <slot name="input" />
      {:else}
        <!-- svelte-ignore a11y-autofocus -->
        {#if type === 'select'}
          <svelte:element
            this={InputComponent}
            id={inputId}
            bind:this={inputEl}
            class={c.input[labelStyleIsFloating]}
            style={inputStyle}
            {name}
            type={needsType ? type : undefined}
            {placeholder}
            {inputmode}
            {size}
            {accept}
            {autocomplete}
            {autocorrect}
            {autocapitalize}
            {spellcheck}
            {autofocus}
            {autosave}
            {disabled}
            {max}
            {maxlength}
            {min}
            {minlength}
            {step}
            {multiple}
            {readonly}
            {required}
            {pattern}
            {tabindex}
            {value}
            on:input={onInput}
            on:change={onChange}
            on:focus={onFocusInternal}
            on:blur={onBlurInternal}
          >
            <slot />
          </svelte:element>
        {:else}
          <svelte:element
            this={InputComponent}
            id={inputId}
            bind:this={inputEl}
            class={c.input[labelStyleIsFloating]}
            style={inputStyle}
            {name}
            type={needsType ? type : undefined}
            {placeholder}
            {inputmode}
            {size}
            {accept}
            {autocomplete}
            {autocorrect}
            {autocapitalize}
            {spellcheck}
            {autofocus}
            {autosave}
            {disabled}
            {max}
            {maxlength}
            {min}
            {minlength}
            {step}
            {multiple}
            {readonly}
            {required}
            {pattern}
            {tabindex}
            {value}
            on:input={onInput}
            on:change={onChange}
            on:focus={onFocusInternal}
            on:blur={onBlurInternal}
          />
        {/if}
      {/if}

      {#if clearButton}
        <DeleteIcon {theme} onClick={onClear} class={c.clearButton} />
      {/if}
      {#if dropdown}
        <DropdownIcon class={c.dropdown} />
      {/if}
    </div>
    <!-- error info content -->
    {#if (error && error !== true) || $$slots.error}
      <div class={cls(c.errorInfo, c.error)}>
        {#if error !== true}{error}{/if}
        <slot name="error" />
      </div>
    {/if}
    {#if (info || $$slots.info) && !error}
      <div class={cls(c.errorInfo, c.info)}>
        {info}
        <slot name="info" />
      </div>
    {/if}
    <!-- error info end -->
  </svelte:fragment>

  {#if type !== 'select'}
    <slot />
  {/if}
</ListItem>
