// react/cjs/components/Messagebar.js
"use strict";

exports.__esModule = true;
exports.default = void 0;
var _react = _interopRequireWildcard(require("react"));
var _useThemeClasses = require("../shared/use-theme-classes.js");
var _useDarkClasses = require("../shared/use-dark-classes.js");
var _MessagebarClasses = require("../../../shared/cjs/classes/MessagebarClasses.js");
var _MessagebarColors = require("../../../shared/cjs/colors/MessagebarColors.js");
var _Toolbar = _interopRequireDefault(require("./Toolbar.js"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { default: e }; }
function _getRequireWildcardCache(e) { if ("function" != typeof WeakMap) return null; var r = new WeakMap(), t = new WeakMap(); return (_getRequireWildcardCache = function (e) { return e ? t : r; })(e); }
function _interopRequireWildcard(e, r) { if (!r && e && e.__esModule) return e; if (null === e || "object" != typeof e && "function" != typeof e) return { default: e }; var t = _getRequireWildcardCache(r); if (t && t.has(e)) return t.get(e); var n = { __proto__: null }, a = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var u in e) if ("default" !== u && {}.hasOwnProperty.call(e, u)) { var i = a ? Object.getOwnPropertyDescriptor(e, u) : null; i && (i.get || i.set) ? Object.defineProperty(n, u, i) : n[u] = e[u]; } return n.default = e, t && t.set(e, n), n; }
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); } // import Link from './Link.js';
const Messagebar = /*#__PURE__*/(0, _react.forwardRef)((props, ref) => {
  const {
    component = 'div',
    className,
    colors: colorsProp,
    id,
    style,
    name,
    placeholder = 'Message',
    value,
    outline = false,
    // eslint-disable-next-line
    leftClassName = '',
    // eslint-disable-next-line
    rightClassName = '',
    textareaId,
    disabled,
    size,
    left,
    right,
    ios,
    material,
    onInput,
    onChange,
    onFocus,
    children,
    ...rest
  } = props;
  const elRef = (0, _react.useRef)(null);
  const areaElRef = (0, _react.useRef)(null);
  (0, _react.useImperativeHandle)(ref, () => ({
    el: elRef.current,
    areaElRef: areaElRef.current
  }));
  const [isFocused, setIsFocused] = (0, _react.useState)(false);
  const themeClasses = (0, _useThemeClasses.useThemeClasses)({
    ios,
    material
  });
  const dark = (0, _useDarkClasses.useDarkClasses)();
  const colors = (0, _MessagebarColors.MessagebarColors)(colorsProp, dark);
  const onFocusInternal = e => {
    setIsFocused(true);
    if (onFocus) onFocus(e);
  };
  const c = themeClasses((0, _MessagebarClasses.MessagebarClasses)({
    ...props
  }, colors, {
    isFocused
  }));
  const Component = component;
  const attrs = {
    ...rest
  };
  return /*#__PURE__*/_react.default.createElement(Component, _extends({
    ref: elRef,
    id: id,
    style: style,
    className: c.base
  }, attrs), /*#__PURE__*/_react.default.createElement(_Toolbar.default, {
    colors: colors,
    outline: outline
  }, left && /*#__PURE__*/_react.default.createElement("div", {
    className: c.left
  }, left), /*#__PURE__*/_react.default.createElement("div", {
    className: c.messagebarArea
  }, /*#__PURE__*/_react.default.createElement("textarea", {
    id: textareaId,
    ref: areaElRef,
    type: "textarea",
    className: c.messagebarInput,
    placeholder: placeholder,
    name: name,
    size: size,
    disabled: disabled,
    onInput: onInput,
    onChange: onChange,
    onFocus: onFocusInternal,
    value: value
  })), right && /*#__PURE__*/_react.default.createElement("div", {
    className: c.right
  }, right)));
});
Messagebar.displayName = 'Messagebar';
var _default = exports.default = Messagebar;

// svelte/components/Messagebar.svelte
<script>
  import { MessagebarClasses } from '../../shared/esm/classes/MessagebarClasses.js';
  import { MessagebarColors } from '../../shared/esm/colors/MessagebarColors.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import Toolbar from './Toolbar.svelte';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let component = 'div';
  export let id = undefined;
  export let name = undefined;
  export let placeholder = 'Message';
  export let value = undefined;
  export let outline = false;
  export let leftClass = '';
  export let rightClass = '';
  export let style = undefined;
  export let textareaId = undefined;
  export let disabled = undefined;
  export let size = undefined;

  export let onInput = undefined;
  export let onChange = undefined;
  export let onFocus = undefined;

  const rippleEl = { current: null };
  let areaEl = null;
  let isFocused = false;

  const dark = useDarkClasses();

  $: colors = MessagebarColors(colorsProp, dark);

  const onFocusInternal = (e) => {
    isFocused = true;
    if (onFocus) onFocus(e);
  };

  $: c = useThemeClasses(
    { ios, material },
    MessagebarClasses(
      {
        leftClass,
        rightClass,
      },
      colors,
      { isFocused }
    ),
    className,
    (v) => (c = v)
  );
</script>

<svelte:element
  this={component}
  {id}
  {style}
  bind:this={rippleEl.current}
  class={c.base}
  {...$$restProps}
>
  <Toolbar {colors} {outline}>
    {#if $$slots.left}
      <div class={c.left}><slot name="left" /></div>
    {/if}
    <div class={c.messagebarArea}>
      <textarea
        id={textareaId}
        bind:this={areaEl}
        type="textarea"
        class={c.messagebarInput}
        {placeholder}
        {name}
        {value}
        {size}
        {disabled}
        on:input={onInput}
        on:change={onChange}
        on:focus={onFocusInternal}
      />
    </div>
    {#if $$slots.right}
      <div class={c.right}><slot name="right" /></div>
    {/if}
  </Toolbar>
</svelte:element>
