// react/esm/components/Message.js
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
/* eslint-disable jsx-a11y/alt-text */
import React, { useRef,
// useState,
forwardRef, useImperativeHandle } from 'react';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { cls } from '../../../shared/esm/cls.js';
// import { useTheme } from '../shared/use-theme.js';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import { MessageClasses } from '../../../shared/esm/classes/MessageClasses.js';
import { MessageColors } from '../../../shared/esm/colors/MessageColors.js';
const Message = /*#__PURE__*/forwardRef((props, ref) => {
  const {
    component = 'div',
    className,
    colors: colorsProp,
    id,
    text,
    name,
    type = 'sent',
    header,
    footer,
    textHeader,
    textFooter,
    avatar,
    ios,
    material,
    children,
    ...rest
  } = props;
  const elRef = useRef(null);
  useImperativeHandle(ref, () => ({
    el: elRef.current
  }));
  // const theme = useTheme({ ios, material });
  const themeClasses = useThemeClasses({
    ios,
    material
  });
  const dark = useDarkClasses();
  const colors = MessageColors(colorsProp, dark);
  const c = themeClasses(MessageClasses({
    ...props
  }, colors));
  const Component = component;
  const attrs = {
    ...rest
  };
  const classes = cls(className, c.message, {
    [c.messageSent]: type === 'sent',
    [c.messageReceived]: type === 'received'
  });
  return /*#__PURE__*/React.createElement(Component, _extends({
    id: id,
    ref: elRef,
    className: classes
  }, attrs), avatar && /*#__PURE__*/React.createElement("div", {
    className: c.messageAvatar
  }, avatar), /*#__PURE__*/React.createElement("div", {
    className: c.messageContent
  }, name && /*#__PURE__*/React.createElement("div", {
    className: c.messageName
  }, name), header && /*#__PURE__*/React.createElement("div", {
    className: c.messageHeader
  }, header), /*#__PURE__*/React.createElement("div", {
    className: c.messageBubble
  }, textHeader && /*#__PURE__*/React.createElement("div", {
    className: c.messageTextHeader
  }, textHeader), text && /*#__PURE__*/React.createElement("div", {
    className: c.messageText
  }, text), textFooter && /*#__PURE__*/React.createElement("div", {
    className: c.messageTextFooter
  }, textFooter)), footer && /*#__PURE__*/React.createElement("div", {
    className: c.messageFooter
  }, footer)));
});
Message.displayName = 'Message';
export default Message;

// svelte/components/Message.svelte
<script>
  import { MessageClasses } from '../../shared/esm/classes/MessageClasses.js';
  import { MessageColors } from '../../shared/esm/colors/MessageColors.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { printText } from '../shared/print-text.js';
  import { cls } from '../../shared/esm/cls.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let component = 'div';
  export let id = undefined;
  export let text = '';
  export let name = undefined;
  export let type = 'sent';
  export let header = '';
  export let footer = '';
  export let textHeader = '';
  export let textFooter = '';
  export let avatar = undefined;

  export let onClick = undefined;

  const rippleEl = { current: null };

  const dark = useDarkClasses();

  $: colors = MessageColors(colorsProp, dark);

  $: c = useThemeClasses(
    { ios, material },
    MessageClasses({ type }, colors),
    className,
    (v) => (c = v)
  );

  $: classes = cls(
    c.message,

    type === 'sent' && c.messageSent,

    type === 'received' && c.messageReceived,

    className
  );
</script>

<svelte:element
  this={component}
  {id}
  bind:this={rippleEl.current}
  class={classes}
  on:click={onClick}
  {...$$restProps}
>
  {#if avatar || $$slots.avatar}
    <div class={c.messageAvatar}>{printText(avatar)}<slot name="avatar" /></div>
  {/if}
  <div class={c.messageContent}>
    {#if name || $$slots.name}
      <div class={c.messageName}>{printText(name)}<slot name="name" /></div>
    {/if}
    {#if header || $$slots.header}
      <div class={c.messageHeader}>
        {printText(header)}<slot name="header" />
      </div>
    {/if}
    <div class={c.messageBubble}>
      {#if textHeader || $$slots.textHeader}
        <div class={c.messageTextHeader}>
          {printText(textHeader)}<slot name="textHeader" />
        </div>
      {/if}
      {#if text || $$slots.text}
        <div class={c.messageText}>{printText(text)}<slot name="text" /></div>
      {/if}
      {#if textFooter || $$slots.textFooter}
        <div class={c.messageTextFooter}>
          {printText(textFooter)}<slot name="textFooter" />
        </div>
      {/if}
    </div>
    {#if footer || $$slots.footer}
      <div class={c.messageFooter}>
        {printText(footer)}<slot name="footer" />
      </div>
    {/if}
  </div>
</svelte:element>
