// vue/components/MessagesTitle.vue
<template>
  <component :is="component" :id="id" ref="elRef" :class="c.base">
    <slot />
  </component>
</template>
<script>
  import { ref, computed } from 'vue';
  import { useContext } from '../shared/use-context.js';

  import { MessagesTitleClasses } from '../../shared/esm/classes/MessagesTitleClasses.js';

  import { MessagesTitleColors } from '../../shared/esm/colors/MessagesTitleColors.js';

  import { themeClasses } from '../shared/use-theme-classes.js';

  import { darkClasses } from '../shared/use-dark-classes.js';

  export default {
    name: 'k-messages-title',
    props: {
      component: {
        type: String,
        default: 'div',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      id: String,
    },
    setup(props) {
      const context = useContext();
      const useDarkClasses = darkClasses(context);
      const useThemeClasses = themeClasses(context);
      const elRef = ref(null);

      const colors = computed(() =>
        MessagesTitleColors(props.colors || {}, useDarkClasses)
      );

      const c = useThemeClasses(props, () =>
        MessagesTitleClasses(
          {
            ...props,
          },
          colors.value
        )
      );

      return {
        c,
        elRef,
      };
    },
  };
</script>

// svelte/components/MessagesTitle.svelte
<script>
  import { MessagesTitleClasses } from '../../shared/esm/classes/MessagesTitleClasses.js';
  import { MessagesTitleColors } from '../../shared/esm/colors/MessagesTitleColors.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let component = 'div';
  export let id = undefined;

  const rippleEl = { current: null };

  const dark = useDarkClasses();

  $: colors = MessagesTitleColors(colorsProp, dark);

  $: c = useThemeClasses(
    { ios, material },
    MessagesTitleClasses({}, colors),
    className,
    (v) => (c = v)
  );
</script>

<svelte:element
  this={component}
  {id}
  bind:this={rippleEl.current}
  class={c.base}
  {...$$restProps}
>
  <slot />
</svelte:element>
