// react/cjs/components/Navbar.js
"use strict";

exports.__esModule = true;
exports.default = void 0;
var _react = _interopRequireWildcard(require("react"));
var _useTheme = require("../shared/use-theme.js");
var _useThemeClasses = require("../shared/use-theme-classes.js");
var _useDarkClasses = require("../shared/use-dark-classes.js");
var _NavbarClasses = require("../../../shared/cjs/classes/NavbarClasses.js");
var _NavbarColors = require("../../../shared/cjs/colors/NavbarColors.js");
function _getRequireWildcardCache(e) { if ("function" != typeof WeakMap) return null; var r = new WeakMap(), t = new WeakMap(); return (_getRequireWildcardCache = function (e) { return e ? t : r; })(e); }
function _interopRequireWildcard(e, r) { if (!r && e && e.__esModule) return e; if (null === e || "object" != typeof e && "function" != typeof e) return { default: e }; var t = _getRequireWildcardCache(r); if (t && t.has(e)) return t.get(e); var n = { __proto__: null }, a = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var u in e) if ("default" !== u && {}.hasOwnProperty.call(e, u)) { var i = a ? Object.getOwnPropertyDescriptor(e, u) : null; i && (i.get || i.set) ? Object.defineProperty(n, u, i) : n[u] = e[u]; } return n.default = e, t && t.set(e, n), n; }
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const Navbar = /*#__PURE__*/(0, _react.forwardRef)((props, ref) => {
  const {
    component = 'div',
    className,
    bgClassName = '',
    innerClassName = '',
    leftClassName = '',
    titleClassName = '',
    subtitleClassName = '',
    rightClassName = '',
    subnavbarClassName = '',
    centerTitle,
    colors: colorsProp,
    translucent = true,
    outline,
    medium,
    large,
    transparent,
    fontSizeIos = 'text-[17px]',
    fontSizeMaterial = 'text-[16px]',
    titleFontSizeIos = 'text-[17px]',
    titleFontSizeMaterial = 'text-[22px]',
    titleMediumFontSizeIos = 'text-[24px]',
    titleMediumFontSizeMaterial = 'text-[24px]',
    titleLargeFontSizeIos = 'text-[34px]',
    titleLargeFontSizeMaterial = 'text-[28px]',
    scrollEl,
    left,
    title,
    subtitle,
    right,
    subnavbar,
    ios,
    material,
    children,
    ...rest
  } = props;
  const elRef = (0, _react.useRef)(null);
  const titleContainerHeight = (0, _react.useRef)(0);
  const bgElRef = (0, _react.useRef)(null);
  const innerElRef = (0, _react.useRef)(null);
  const titleContainerElRef = (0, _react.useRef)(null);
  const titleElRef = (0, _react.useRef)(null);
  const subnavbarElRef = (0, _react.useRef)(null);
  const wasScrollable = (0, _react.useRef)(null);
  (0, _react.useImperativeHandle)(ref, () => ({
    el: elRef.current
  }));
  const Component = component;
  const theme = (0, _useTheme.useTheme)({
    ios,
    material
  });
  const themeClasses = (0, _useThemeClasses.useThemeClasses)({
    ios,
    material
  });
  const dark = (0, _useDarkClasses.useDarkClasses)();
  const attrs = {
    ...rest
  };
  const colors = (0, _NavbarColors.NavbarColors)(colorsProp, dark);
  const onScroll = e => {
    const {
      scrollTop
    } = e.target;
    if (!transparent && !large && !medium) {
      if (wasScrollable.current) {
        if (titleElRef.current) {
          titleElRef.current.style.opacity = '';
        }
        if (bgElRef.current) {
          bgElRef.current.style.opacity = '';
        }
      }
      return;
    }
    const maxTranslate = titleContainerHeight.current;
    const scrollProgress = Math.max(Math.min(scrollTop / maxTranslate, 1), 0);
    bgElRef.current.style.opacity = transparent ? -0.5 + scrollProgress * 1.5 : '';
    if (medium || large) {
      bgElRef.current.style.transform = `translateY(-${scrollProgress * maxTranslate}px)`;
    }
    if (titleContainerElRef.current) {
      titleContainerElRef.current.style.transform = `translateY(-${scrollProgress * maxTranslate}px)`;
      titleContainerElRef.current.style.opacity = 1 - scrollProgress * 2;
    }
    if (titleElRef.current) {
      titleElRef.current.style.opacity = -0.5 + scrollProgress * 1.5;
    }
    if ((medium || large) && subnavbarElRef.current) {
      subnavbarElRef.current.style.transform = `translateY(-${scrollProgress * maxTranslate}px)`;
    }
  };
  const getScrollEl = () => {
    if (typeof scrollEl === 'undefined') {
      return elRef.current && elRef.current.parentNode;
    }
    return scrollEl.current || scrollEl;
  };
  const initScroll = () => {
    if (!large && !medium && !transparent) {
      if (wasScrollable.current) {
        onScroll({
          target: {
            scrollTop: 0
          }
        });
        wasScrollable.current = false;
      }
      return;
    }
    wasScrollable.current = true;
    if (titleContainerElRef.current) {
      titleContainerHeight.current = titleContainerElRef.current.offsetHeight;
    } else {
      titleContainerHeight.current = innerElRef.current.offsetHeight;
    }
    const scrollElLocal = getScrollEl();
    if (scrollElLocal) {
      scrollElLocal.addEventListener('scroll', onScroll);
      onScroll({
        target: scrollElLocal
      });
    } else {
      onScroll({
        target: {
          scrollTop: 0
        }
      });
    }
  };
  const destroyScroll = () => {
    const scrollElLocal = getScrollEl();
    if (scrollElLocal) {
      scrollElLocal.removeEventListener('scroll', onScroll);
    }
  };
  (0, _react.useEffect)(() => {
    initScroll();
    return destroyScroll;
  });
  const isOutline = typeof outline === 'undefined' ? theme === 'ios' : outline;
  const c = themeClasses((0, _NavbarClasses.NavbarClasses)({
    ...props,
    centerTitle: typeof centerTitle === 'undefined' ? theme === 'ios' : centerTitle,
    translucent,
    outline: isOutline,
    fontSizeIos,
    fontSizeMaterial,
    titleFontSizeIos,
    titleFontSizeMaterial,
    titleMediumFontSizeIos,
    titleMediumFontSizeMaterial,
    titleLargeFontSizeIos,
    titleLargeFontSizeMaterial,
    bgClassName,
    innerClassName,
    leftClassName,
    titleClassName,
    subtitleClassName,
    rightClassName,
    subnavbarClassName
  }, colors, className), className);
  return /*#__PURE__*/_react.default.createElement(Component, _extends({
    ref: elRef,
    className: c.base
  }, attrs), /*#__PURE__*/_react.default.createElement("div", {
    className: c.bg,
    ref: bgElRef
  }), /*#__PURE__*/_react.default.createElement("div", {
    className: c.inner,
    ref: innerElRef
  }, left && /*#__PURE__*/_react.default.createElement("div", {
    className: c.left
  }, left), (title || subtitle) && /*#__PURE__*/_react.default.createElement("div", {
    className: c.title,
    ref: titleElRef
  }, title, subtitle && /*#__PURE__*/_react.default.createElement("div", {
    className: c.subtitle
  }, subtitle)), right && /*#__PURE__*/_react.default.createElement("div", {
    className: c.right
  }, right), children), (large || medium) && /*#__PURE__*/_react.default.createElement("div", {
    className: c.titleContainer,
    ref: titleContainerElRef
  }, title), subnavbar && /*#__PURE__*/_react.default.createElement("div", {
    className: c.subnavbar,
    ref: subnavbarElRef
  }, subnavbar));
});
Navbar.displayName = 'Navbar';
var _default = exports.default = Navbar;

// svelte/components/Navbar.svelte
<script>
  import { onMount, onDestroy, afterUpdate } from 'svelte';
  import { useTheme } from '../shared/use-theme.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { NavbarClasses } from '../../shared/esm/classes/NavbarClasses.js';
  import { NavbarColors } from '../../shared/esm/colors/NavbarColors.js';
  import { printText } from '../shared/print-text.js';

  let className = undefined;
  export { className as class };

  export let bgClass = '';
  export let innerClass = '';
  export let leftClass = '';
  export let titleClass = '';
  export let subtitleClass = '';
  export let rightClass = '';
  export let subnavbarClass = '';

  let colorsProp = undefined;
  export { colorsProp as colors };
  export let translucent = true;
  export let outline = undefined;
  export let centerTitle = undefined;

  export let medium = false;
  export let large = false;
  export let transparent = false;

  export let fontSizeIos = 'text-[17px]';
  export let fontSizeMaterial = 'text-[16px]';

  export let titleFontSizeIos = 'text-[17px]';
  export let titleFontSizeMaterial = 'text-[22px]';

  export let titleMediumFontSizeIos = 'text-[24px]';
  export let titleMediumFontSizeMaterial = 'text-[24px]';

  export let titleLargeFontSizeIos = 'text-[34px]';
  export let titleLargeFontSizeMaterial = 'text-[28px]';

  export let scrollEl = undefined;

  export let title = undefined;
  export let subtitle = undefined;
  export let ios = undefined;
  export let material = undefined;

  let elRef = 0;
  let titleContainerHeight = 0;
  let bgElRef = null;
  let innerElRef = null;
  let titleContainerElRef = null;
  let titleElRef = null;
  let subnavbarElRef = null;

  $: isScrollable = medium || large || transparent;
  let wasScrollable = isScrollable;

  const dark = useDarkClasses();

  let theme;
  theme = useTheme((v) => (theme = v));

  $: colors = NavbarColors(colorsProp, dark);

  $: isOutline = typeof outline === 'undefined' ? theme === 'ios' : outline;

  $: c = useThemeClasses(
    { ios, material },
    NavbarClasses(
      {
        bgClass,
        innerClass,
        leftClass,
        titleClass,
        subtitleClass,
        rightClass,
        subnavbarClass,
        translucent,
        transparent,
        outline: isOutline,
        fontSizeIos,
        fontSizeMaterial,
        titleFontSizeIos,
        titleFontSizeMaterial,
        medium,
        large,
        titleMediumFontSizeIos,
        titleMediumFontSizeMaterial,
        titleLargeFontSizeIos,
        titleLargeFontSizeMaterial,
        centerTitle:
          typeof centerTitle === 'undefined' ? theme === 'ios' : centerTitle,
      },
      colors,
      className
    ),
    className,
    (v) => (c = v)
  );

  const getScrollEl = () => {
    if (typeof scrollEl === 'undefined') {
      return elRef && elRef.parentNode;
    }
    return scrollEl || scrollEl;
  };

  const onScroll = (e) => {
    if (!e) {
      e = {
        target: getScrollEl(),
      };
    }
    const { scrollTop } = e.target;
    if (!isScrollable) {
      if (wasScrollable) {
        if (titleElRef) {
          titleElRef.style.opacity = '';
        }
        if (bgElRef) {
          bgElRef.style.opacity = '';
        }
      }
      return;
    }

    const maxTranslate = titleContainerHeight;
    const scrollProgress = Math.max(Math.min(scrollTop / maxTranslate, 1), 0);

    bgElRef.style.opacity = transparent ? -0.5 + scrollProgress * 1.5 : '';
    if (medium || large) {
      bgElRef.style.transform = `translateY(-${
        scrollProgress * maxTranslate
      }px)`;
    }

    if (titleContainerElRef) {
      titleContainerElRef.style.transform = `translateY(-${
        scrollProgress * maxTranslate
      }px)`;
      titleContainerElRef.style.opacity = 1 - scrollProgress * 2;
    }
    if (titleElRef) {
      titleElRef.style.opacity = -0.5 + scrollProgress * 1.5;
    }
    if ((medium || large) && subnavbarElRef) {
      subnavbarElRef.style.transform = `translateY(-${
        scrollProgress * maxTranslate
      }px)`;
    }
  };

  const calcSize = () => {
    if (titleContainerElRef) {
      titleContainerHeight = titleContainerElRef.offsetHeight;
    } else {
      titleContainerHeight = innerElRef.offsetHeight;
    }
  };

  const initScroll = () => {
    if (!isScrollable) {
      if (wasScrollable) {
        onScroll({ target: { scrollTop: 0 } });
        wasScrollable = isScrollable;
      }
      return;
    }
    wasScrollable = isScrollable;

    const scrollElLocal = getScrollEl();
    if (scrollElLocal) {
      scrollElLocal.addEventListener('scroll', onScroll);
      onScroll({ target: scrollElLocal });
    } else {
      onScroll({ target: { scrollTop: 0 } });
    }
  };

  const destroyScroll = () => {
    const scrollElLocal = getScrollEl();
    if (scrollElLocal) {
      scrollElLocal.removeEventListener('scroll', onScroll);
    }
  };

  afterUpdate(() => {
    calcSize();
    if (!wasScrollable && isScrollable) {
      initScroll();
    } else if (wasScrollable && !isScrollable) {
      onScroll();
      wasScrollable = isScrollable;
      destroyScroll();
    } else if (wasScrollable && isScrollable) {
      onScroll();
    }
  });
  onMount(() => {
    calcSize();
    initScroll();
  });
  onDestroy(() => {
    destroyScroll();
  });
</script>

<div class={c.base} bind:this={elRef} {...$$restProps}>
  <div class={c.bg} bind:this={bgElRef} />
  <div class={c.inner} bind:this={innerElRef}>
    {#if $$slots.left}
      <div class={c.left}><slot name="left" /></div>
    {/if}
    {#if $$slots.title || $$slots.subtitle || title || subtitle}
      <div class={c.title} bind:this={titleElRef}>
        {printText(title)}
        <slot name="title" />
        {#if subtitle || $$slots.subtitle}
          <div class={c.subtitle}>
            {printText(subtitle)}<slot name="subtitle" />
          </div>
        {/if}
      </div>
    {/if}
    {#if $$slots.right}
      <div class={c.right}><slot name="right" /></div>
    {/if}
    <slot />
  </div>
  {#if large || medium}
    <div class={c.titleContainer} bind:this={titleContainerElRef}>
      {printText(title)}
      <slot name="title" />
    </div>
  {/if}
  {#if $$slots.subnavbar}
    <div class={c.subnavbar} bind:this={subnavbarElRef}>
      <slot name="subnavbar" />
    </div>
  {/if}
</div>
