// vue/components/NavbarBackLink.vue
<template>
  <k-link :component="component" :class="c.base" navbar>
    <span :class="c.icon">
      <k-back-icon :theme="theme" />
    </span>
    <span v-if="shouldShowText">{{ text }}</span>
    <slot />
  </k-link>
</template>
<script>
  import { computed } from 'vue';
  import { useContext } from '../shared/use-context.js';

  import { useTheme } from '../shared/use-theme.js';

  import { themeClasses } from '../shared/use-theme-classes.js';
  import kBackIcon from './icons/BackIcon.vue';
  import kLink from './Link.vue';

  import { NavbarBackLinkClasses } from '../../shared/esm/classes/NavbarBackLinkClasses.js';

  export default {
    name: 'k-navbar-back-link',
    components: {
      kLink,
      kBackIcon,
    },
    props: {
      component: {
        type: String,
        default: 'a',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      text: {
        type: String,
        default: 'Back',
      },
      showText: {
        type: [Boolean, String],
        default: 'auto',
      },
    },
    setup(props) {
      const context = useContext();
      const useThemeClasses = themeClasses(context);
      const theme = useTheme(props, context);
      const shouldShowText = computed(
        () =>
          (props.showText === 'auto' && theme.value === 'ios') ||
          props.showText === true
      );
      const c = useThemeClasses(props, () => NavbarBackLinkClasses());
      return {
        c,
        shouldShowText,
        theme,
      };
    },
  };
</script>

// svelte/components/NavbarBackLink.svelte
<script>
  import { useTheme } from '../shared/use-theme.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import BackIcon from './icons/BackIcon.svelte';
  import Link from './Link.svelte';
  import { NavbarBackLinkClasses } from '../../shared/esm/classes/NavbarBackLinkClasses.js';
  import { printText } from '../shared/print-text.js';

  let className = undefined;
  export { className as class };
  export let ios = undefined;
  export let material = undefined;

  export let component = 'a';
  export let text = 'Back';
  export let showText = 'auto';
  export let onClick = undefined;

  let theme;
  theme = useTheme({ ios, material }, (v) => (theme = v));

  $: shouldShowText =
    (showText === 'auto' && theme === 'ios') || showText === true;

  $: c = useThemeClasses(
    { ios, material },
    NavbarBackLinkClasses(),
    className,
    (v) => (c = v)
  );
</script>

<Link class={c.base} navbar {component} {...$$restProps} {onClick}>
  <span class={c.icon}>
    <BackIcon {theme} />
  </span>
  {#if shouldShowText}
    <span>{printText(text)}</span>
  {/if}
  <slot />
</Link>
