// vue/components/Notification.vue
<template>
  <component :is="component" v-if="theme === 'ios'" ref="elRef" :class="c.base">
    <div :class="c.header">
      <div v-if="icon || slots.icon" :class="c.icon">
        {{ icon }}<slot name="icon" />
      </div>
      <div v-if="title || slots.title" :class="c.title">
        {{ title }}<slot name="title" />
      </div>
      <div
        v-if="titleRightText || slots.titleRightText"
        :class="c.titleRightText"
      >
        {{ titleRightText }}<slot name="titleRightText" />
      </div>
      <div
        v-if="button || slots.button"
        :class="c.button"
        role="button"
        tabindex="0"
        @click="onClose"
      >
        <delete-icon :theme="theme" :class="c.deleteIcon" />
        <slot name="button" />
      </div>
    </div>
    <div :class="c.content">
      <div v-if="subtitle || slots.subtitle" :class="c.subtitle">
        {{ subtitle }}<slot name="subtitle" />
      </div>
      <div v-if="text || slots.text" :class="c.text">
        {{ text }}<slot name="text" />
      </div>
      <slot />
    </div>
  </component>
  <component :is="component" v-else ref="elRef" :class="c.base">
    <div :class="c.header">
      <div v-if="icon || slots.icon" :class="c.icon">
        {{ icon }}<slot name="icon" />
      </div>
      <div :class="c.contentWrapper">
        <div :class="c.contentTitle">
          <div v-if="title || slots.title" :class="c.title">
            {{ title }}<slot name="title" />
          </div>
          <div
            v-if="titleRightText || slots.titleRightText"
            :class="c.titleRightText"
          >
            {{ titleRightText }}<slot name="titleRightText" />
          </div>
        </div>
        <div :class="c.content">
          <div v-if="subtitle || slots.subtitle" :class="c.subtitle">
            {{ subtitle }}<slot name="subtitle" />
          </div>
          <div v-if="text || slots.text" :class="c.text">
            {{ text }}<slot name="text" />
          </div>
          <slot />
        </div>
      </div>
      <div
        v-if="button || slots.button"
        :class="c.button"
        role="button"
        tabindex="0"
        @click="onClose"
      >
        <delete-icon :theme="theme" :class="c.deleteIcon" />
        <slot name="button" />
      </div>
    </div>
  </component>
</template>
<script>
  import { computed } from 'vue';
  import { useContext } from '../shared/use-context.js';

  import { NotificationsClasses } from '../../shared/esm/classes/NotificationsClasses.js';

  import { NotificationsColors } from '../../shared/esm/colors/NotificationsColors.js';

  import { darkClasses } from '../shared/use-dark-classes.js';

  import { themeClasses } from '../shared/use-theme-classes.js';

  import { useTheme } from '../shared/use-theme.js';
  import DeleteIcon from './icons/DeleteIcon.vue';

  export default {
    name: 'k-notification',
    components: {
      DeleteIcon,
    },
    props: {
      component: {
        type: String,
        default: 'div',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      opened: {
        type: Boolean,
        default: undefined,
      },
      translucent: {
        type: Boolean,
        default: true,
      },
      button: { type: String },
      icon: { type: String },
      title: { type: [String, Number] },
      titleRightText: { type: [String, Number] },
      subtitle: { type: [String, Number] },
      text: { type: [String, Number] },
    },
    emits: ['close'],
    setup(props, ctx) {
      const context = useContext();
      const useDarkClasses = darkClasses(context);
      const useThemeClasses = themeClasses(context);
      const theme = useTheme({}, context);

      const colors = computed(() =>
        NotificationsColors(props.colors || {}, useDarkClasses)
      );

      const c = useThemeClasses(props, () =>
        NotificationsClasses(props, colors.value, ctx.attrs.class)
      );
      const onClose = () => {
        ctx.emit('close');
      };
      return {
        c,
        theme,
        onClose,
        slots: ctx.slots,
      };
    },
  };
</script>

// svelte/components/Notification.svelte
<script>
  import { NotificationsClasses } from '../../shared/esm/classes/NotificationsClasses.js';
  import { NotificationsColors } from '../../shared/esm/colors/NotificationsColors.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { printText } from '../shared/print-text.js';
  import { useTheme } from '../shared/use-theme.js';

  import DeleteIcon from './icons/DeleteIcon.svelte';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;
  export let translucent = true;
  export let onClick = undefined;
  export let onClose = undefined;

  export let button = undefined;
  export let title = '';
  export let titleRightText = '';
  export let subtitle = '';
  export let text = '';

  export let opened = false;

  const dark = useDarkClasses();
  let theme;
  theme = useTheme({}, (v) => (theme = v));

  $: colors = NotificationsColors(colorsProp, dark);

  $: c = useThemeClasses(
    { ios, material },
    NotificationsClasses({ opened, translucent }, colors, className),
    className,
    (v) => (c = v)
  );
</script>

{#if theme === 'ios'}
  <div class={c.base} {...$$restProps} on:click={onClick}>
    <div class={c.header}>
      {#if $$slots.icon}
        <div class={c.icon}><slot name="icon" /></div>
      {/if}
      {#if title || $$slots.title}
        <div class={c.title}>{printText(title)}<slot name="title" /></div>
      {/if}
      {#if titleRightText || $$slots.titleRightText}
        <div class={c.titleRightText}>
          {printText(titleRightText)}<slot name="titleRightText" />
        </div>
      {/if}
      {#if button || $$slots.button}
        <div class={c.button} role="button" tabindex="0" on:click={onClose}>
          <DeleteIcon {theme} class={c.deleteIcon} />
          <slot name="button" />
        </div>
      {/if}
    </div>
    <div class={c.content}>
      {#if subtitle || $$slots.subtitle}
        <div class={c.subtitle}>
          {printText(subtitle)}<slot name="subtitle" />
        </div>
      {/if}
      {#if text || $$slots.text}
        <div class={c.text}>{printText(text)}<slot name="text" /></div>
      {/if}
      <slot />
    </div>
  </div>
{:else}
  <div class={c.base} {...$$restProps} on:click={onClick}>
    <div class={c.header}>
      {#if $$slots.icon}
        <div class={c.icon}><slot name="icon" /></div>
      {/if}
      <div class={c.contentWrapper}>
        <div class={c.contentTitle}>
          {#if title || $$slots.title}
            <div class={c.title}>{printText(title)}<slot name="title" /></div>
          {/if}
          {#if titleRightText || $$slots.titleRightText}
            <div class={c.titleRightText}>
              {printText(titleRightText)}<slot name="titleRightText" />
            </div>
          {/if}
        </div>
        <div class={c.content}>
          {#if subtitle || $$slots.subtitle}
            <div class={c.subtitle}>
              {printText(subtitle)}<slot name="subtitle" />
            </div>
          {/if}
          {#if text || $$slots.text}
            <div class={c.text}>{printText(text)}<slot name="text" /></div>
          {/if}
          <slot />
        </div>
      </div>
      {#if button || $$slots.button}
        <div class={c.button} role="button" tabindex="0" on:click={onClose}>
          <DeleteIcon {theme} class={c.deleteIcon} />
          <slot name="button" />
        </div>
      {/if}
    </div>
  </div>
{/if}
