// react/esm/components/Searchbar.js
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
/* eslint-disable no-console */
import React, { useRef, useState, forwardRef, useImperativeHandle, useEffect } from 'react';
import { SearchbarClasses } from '../../../shared/esm/classes/SearchbarClasses.js';
import { SearchbarColors } from '../../../shared/esm/colors/SearchbarColors.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { cls } from '../../../shared/esm/cls.js';
import { useTheme } from '../shared/use-theme.js';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import DeleteIcon from './icons/DeleteIcon.js';
import SearchIcon from './icons/SearchIcon.js';
import BackIcon from './icons/BackIcon.js';
const Searchbar = /*#__PURE__*/forwardRef((props, ref) => {
  const {
    component = 'div',
    className,
    colors: colorsProp,
    placeholder = 'Search',
    value,
    inputId,
    inputStyle,
    disableButton = false,
    disableButtonText = 'Cancel',
    clearButton = true,
    onInput,
    onChange,
    onFocus,
    onBlur,
    onClear,
    onDisable,
    ios,
    material,
    // children,
    ...rest
  } = props;
  const searchElRef = useRef(null);
  const elRef = useRef(null);
  const disableButtonRef = useRef(null);
  const [disableButtonWidth, setDisableButtonWidth] = useState(0);
  const disableTimeout = useRef(null);
  const allowTransition = useRef(false);
  useImperativeHandle(ref, () => ({
    el: elRef.current,
    searchEl: searchElRef.current
  }));
  const [isEnabled, setIsEnabled] = useState(false);
  const theme = useTheme({
    ios,
    material
  });
  const themeClasses = useThemeClasses({
    ios,
    material
  });
  const dark = useDarkClasses();
  const colors = SearchbarColors(colorsProp, dark);
  const handleInput = e => {
    if (onInput) onInput(e);
  };
  const handleChange = e => {
    if (onChange) onChange(e);
  };
  const handleFocus = e => {
    setIsEnabled(true);
    if (onFocus) onFocus(e);
  };
  const handleBlur = e => {
    if (onBlur) onBlur(e);
  };
  const onGlobalBlur = () => {
    if (!value) {
      disableTimeout.current = setTimeout(() => {
        setIsEnabled(false);
      });
    }
  };
  const onGlobalFocus = () => {
    clearTimeout(disableTimeout.current);
  };
  const handleDisableButton = e => {
    e.preventDefault();
    setIsEnabled(false);
    if (searchElRef.current) {
      searchElRef.current.blur();
    }
    if (onDisable) onDisable();
    if (onClear) onClear();
  };
  useEffect(() => {
    if (disableButtonRef.current) {
      setDisableButtonWidth(disableButtonRef.current.offsetWidth);
    }
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        allowTransition.current = true;
      });
    });
  }, []);
  const c = themeClasses(SearchbarClasses({
    ...props
  }, colors, {
    isEnabled,
    darkClasses: dark
  }));
  const CancelButton = theme === 'ios' ? /*#__PURE__*/React.createElement("button", {
    type: "button",
    ref: disableButtonRef,
    style: {
      marginRight: isEnabled ? 0 : `-${disableButtonWidth}px`,
      transitionDuration: !allowTransition.current ? '0ms' : ''
    },
    className: c.cancelButton,
    onClick: handleDisableButton,
    onPointerDown: e => e.preventDefault()
  }, disableButtonText) : /*#__PURE__*/React.createElement(BackIcon, {
    theme: theme,
    onClick: handleDisableButton,
    className: cls(c.cancelButton),
    onPointerDown: e => e.preventDefault()
  });
  const Component = component;
  const attrs = {
    ...rest
  };
  return /*#__PURE__*/React.createElement(Component, _extends({
    ref: elRef,
    className: c.base
  }, attrs, {
    onBlurCapture: onGlobalBlur,
    onFocusCapture: onGlobalFocus
  }), /*#__PURE__*/React.createElement("div", {
    className: c.inner
  }, /*#__PURE__*/React.createElement("span", {
    className: c.searchIconWrap
  }, /*#__PURE__*/React.createElement(SearchIcon, {
    ios: ios,
    material: material,
    className: c.searchIcon
  })), /*#__PURE__*/React.createElement("input", {
    id: inputId,
    ref: searchElRef,
    className: cls(c.input),
    style: inputStyle,
    type: "text",
    name: "search",
    placeholder: placeholder,
    value: value,
    onInput: handleInput,
    onChange: handleChange,
    onFocus: handleFocus,
    onBlur: handleBlur
  }), value && clearButton && /*#__PURE__*/React.createElement("button", {
    className: c.clearButton,
    onClick: onClear,
    type: "button"
  }, /*#__PURE__*/React.createElement(DeleteIcon, {
    theme: theme,
    className: c.deleteIcon
  }))), disableButton && CancelButton);
});
Searchbar.displayName = 'Searchbar';
export default Searchbar;

// svelte/components/Searchbar.svelte
<script>
  import { onMount } from 'svelte';
  import { useTheme } from '../shared/use-theme.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import DeleteIcon from './icons/DeleteIcon.svelte';
  import SearchIcon from './icons/SearchIcon.svelte';
  import BackIcon from './icons/BackIcon.svelte';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { SearchbarClasses } from '../../shared/esm/classes/SearchbarClasses.js';
  import { SearchbarColors } from '../../shared/esm/colors/SearchbarColors.js';
  import { cls } from '../../shared/esm/cls.js';
  import { useTouchRipple } from '../shared/use-touch-ripple.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let component = 'div';

  export let placeholder = 'Search';
  export let value = undefined;
  export let inputId = undefined;
  export let inputStyle = undefined;

  export let disableButton = false;
  export let disableButtonText = 'Cancel';
  export let clearButton = true;

  export let onInput = undefined;
  export let onChange = undefined;
  export let onFocus = undefined;
  export let onBlur = undefined;
  export let onClear = undefined;
  export let onDisable = undefined;
  export let touchRipple = true;

  let theme;
  theme = useTheme({ ios, material }, (v) => (theme = v));

  let searchEl = null;
  const rippleEl = { current: null };
  $: useTouchRipple(rippleEl, touchRipple);

  let isEnabled = false;
  let disableButtonRef = null;
  let disableButtonWidth = 0;
  let disableTimeout = null;
  let allowTransition = false;

  const dark = useDarkClasses();

  $: colors = SearchbarColors(colorsProp, dark);

  const handleInput = (e) => {
    if (onInput) onInput(e);
  };

  const handleChange = (e) => {
    if (onChange) onChange(e);
  };

  const handleFocus = (e) => {
    isEnabled = true;
    if (onFocus) onFocus(e);
  };

  const handleBlur = (e) => {
    if (onBlur) onBlur(e);
  };

  const onGlobalBlur = () => {
    if (!value) {
      disableTimeout = setTimeout(() => {
        isEnabled = false;
      });
    }
  };

  const onGlobalFocus = () => {
    clearTimeout(disableTimeout);
  };

  const handleDisableButton = (e) => {
    e.preventDefault();
    isEnabled = false;
    if (searchEl) {
      searchEl.blur();
    }
    if (onDisable) onDisable();
    if (onClear) onClear();
  };

  onMount(() => {
    if (disableButtonRef) {
      disableButtonWidth = disableButtonRef.offsetWidth;
    }
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        allowTransition = true;
      });
    });
  });

  $: c = useThemeClasses(
    { ios, material },
    SearchbarClasses({}, colors, {
      isEnabled,
      darkClasses: dark,
    }),
    className,
    (v) => (c = v)
  );
</script>

<svelte:element
  this={component}
  bind:this={rippleEl.current}
  class={c.base}
  on:blurCapture={onGlobalBlur}
  on:focusCapture={onGlobalFocus}
  {...$$restProps}
>
  <div class={c.inner}>
    <span class={c.searchIconWrap}>
      <SearchIcon {theme} class={c.searchIcon} />
    </span>
    <input
      id={inputId}
      bind:this={searchEl}
      class={cls(c.input)}
      style={inputStyle}
      type="text"
      name="search"
      {placeholder}
      {value}
      on:input={handleInput}
      on:change={handleChange}
      on:focus={handleFocus}
      on:blur={handleBlur}
    />
    {#if value && clearButton}
      <button class={c.clearButton} on:click={onClear} type="button">
        <DeleteIcon {theme} class={c.deleteIcon} />
      </button>
    {/if}
  </div>
  {#if disableButton}
    {#if theme === 'ios'}
      <button
        type="button"
        bind:this={disableButtonRef}
        style="margin-right: {isEnabled
          ? 0
          : `-${disableButtonWidth}px`}; transition-duration: {!allowTransition
          ? '0ms'
          : ''};"
        class={c.cancelButton}
        on:click={handleDisableButton}
        on:pointerdown|preventDefault
      >
        {disableButtonText}
      </button>
    {:else}
      <button
        type="button"
        on:click={handleDisableButton}
        on:pointerdown|preventDefault
        class={cls(c.cancelButton)}
      >
        <BackIcon {theme} on:click={handleDisableButton} />
      </button>
    {/if}
  {/if}
</svelte:element>
