// react/cjs/components/TabbarLink.js
"use strict";

exports.__esModule = true;
exports.default = void 0;
var _react = _interopRequireWildcard(require("react"));
var _TabbarLinkClasses = require("../../../shared/cjs/classes/TabbarLinkClasses.js");
var _TabbarLinkColors = require("../../../shared/cjs/colors/TabbarLinkColors.js");
var _useDarkClasses = require("../shared/use-dark-classes.js");
var _useThemeClasses = require("../shared/use-theme-classes.js");
var _Link = _interopRequireDefault(require("./Link.js"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { default: e }; }
function _getRequireWildcardCache(e) { if ("function" != typeof WeakMap) return null; var r = new WeakMap(), t = new WeakMap(); return (_getRequireWildcardCache = function (e) { return e ? t : r; })(e); }
function _interopRequireWildcard(e, r) { if (!r && e && e.__esModule) return e; if (null === e || "object" != typeof e && "function" != typeof e) return { default: e }; var t = _getRequireWildcardCache(r); if (t && t.has(e)) return t.get(e); var n = { __proto__: null }, a = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var u in e) if ("default" !== u && {}.hasOwnProperty.call(e, u)) { var i = a ? Object.getOwnPropertyDescriptor(e, u) : null; i && (i.get || i.set) ? Object.defineProperty(n, u, i) : n[u] = e[u]; } return n.default = e, t && t.set(e, n), n; }
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const TabbarLink = /*#__PURE__*/(0, _react.forwardRef)((props, ref) => {
  const {
    className,
    active,
    ios,
    material,
    colors: colorsProp,
    linkProps = {},
    icon,
    label,
    children,
    ...rest
  } = props;
  const elRef = (0, _react.useRef)(null);
  (0, _react.useImperativeHandle)(ref, () => ({
    el: elRef.current
  }));
  const attrs = {
    ...linkProps,
    ...rest
  };
  const dark = (0, _useDarkClasses.useDarkClasses)();
  const colors = (0, _TabbarLinkColors.TabbarLinkColors)(colorsProp, dark);
  const themeClasses = (0, _useThemeClasses.useThemeClasses)({
    ios,
    material
  });
  const hasIcon = !!icon;
  const hasLabel = label || children && children.length;
  const c = themeClasses((0, _TabbarLinkClasses.TabbarLinkClasses)({
    hasLabel,
    hasIcon,
    active
  }, colors));
  return /*#__PURE__*/_react.default.createElement(_Link.default, _extends({
    ref: elRef,
    tabbar: true,
    tabbarActive: active,
    className: className
  }, attrs), /*#__PURE__*/_react.default.createElement("span", {
    className: c.content
  }, icon && /*#__PURE__*/_react.default.createElement("span", {
    className: c.iconContainer
  }, /*#__PURE__*/_react.default.createElement("span", {
    className: c.iconBg
  }), icon), (label || children && children.length) && /*#__PURE__*/_react.default.createElement("span", {
    className: c.label
  }, label, children)));
});
TabbarLink.displayName = 'TabbarLink';
var _default = exports.default = TabbarLink;

// svelte/components/TabbarLink.svelte
<script>
  import { TabbarLinkClasses } from '../../shared/esm/classes/TabbarLinkClasses.js';
  import { TabbarLinkColors } from '../../shared/esm/colors/TabbarLinkColors.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { printText } from '../shared/print-text.js';

  import Link from './Link.svelte';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;
  export let linkProps = {};

  export let active = false;
  export let label = undefined;

  const dark = useDarkClasses();

  $: colors = TabbarLinkColors(colorsProp, dark);

  $: hasIcon = $$slots.icon;
  $: hasLabel = label || $$slots.label || $$slots.default;

  $: c = useThemeClasses(
    { ios, material },
    TabbarLinkClasses({ hasLabel, hasIcon, active }, colors),
    '',
    (v) => (c = v)
  );
</script>

<Link
  tabbar
  tabbarActive={active}
  class={className}
  {...$$restProps}
  {...linkProps}
>
  <span class={c.content}>
    {#if hasIcon}
      <span class={c.iconContainer}>
        <span class={c.iconBg} />
        <slot name="icon" />
      </span>
    {/if}
    {#if hasLabel}
      <span class={c.label}>
        {#if $$slots.label}
          <slot name="label" />
        {:else}
          {printText(label)}
          <slot />
        {/if}
      </span>
    {/if}
  </span>
</Link>
