// vue/components/TableBody.vue
<template>
  <tbody ref="elRef" :class="c.base">
    <slot />
  </tbody>
</template>
<script>
  import { ref } from 'vue';
  import { useContext } from '../shared/use-context.js';

  import { TableBodyClasses } from '../../shared/esm/classes/TableBodyClasses.js';

  import { themeClasses } from '../shared/use-theme-classes.js';

  export default {
    name: 'k-table-body',
    props: {
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
    },
    setup(props, ctx) {
      const context = useContext();
      const useThemeClasses = themeClasses(context);
      const elRef = ref(null);

      const c = useThemeClasses(props, () =>
        TableBodyClasses(
          {
            ...props,
          },
          ctx.attrs.class
        )
      );

      return {
        c,
        elRef,
      };
    },
  };
</script>

// svelte/components/TableBody.svelte
<script>
  import { TableBodyClasses } from '../../shared/esm/classes/TableBodyClasses.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  let className = undefined;
  export { className as class };

  export let ios = undefined;
  export let material = undefined;

  const rippleEl = { current: null };

  $: c = useThemeClasses(
    { ios, material },
    TableBodyClasses({}),
    className,
    (v) => (c = v)
  );
</script>

<tbody bind:this={rippleEl.current} class={c.base} {...$$restProps}>
  <slot />
</tbody>
