// react/cjs/components/TableRow.js
"use strict";

exports.__esModule = true;
exports.default = void 0;
var _react = _interopRequireWildcard(require("react"));
var _useThemeClasses = require("../shared/use-theme-classes.js");
var _useDarkClasses = require("../shared/use-dark-classes.js");
var _TableRowClasses = require("../../../shared/cjs/classes/TableRowClasses.js");
var _TableRowColors = require("../../../shared/cjs/colors/TableRowColors.js");
function _getRequireWildcardCache(e) { if ("function" != typeof WeakMap) return null; var r = new WeakMap(), t = new WeakMap(); return (_getRequireWildcardCache = function (e) { return e ? t : r; })(e); }
function _interopRequireWildcard(e, r) { if (!r && e && e.__esModule) return e; if (null === e || "object" != typeof e && "function" != typeof e) return { default: e }; var t = _getRequireWildcardCache(r); if (t && t.has(e)) return t.get(e); var n = { __proto__: null }, a = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var u in e) if ("default" !== u && {}.hasOwnProperty.call(e, u)) { var i = a ? Object.getOwnPropertyDescriptor(e, u) : null; i && (i.get || i.set) ? Object.defineProperty(n, u, i) : n[u] = e[u]; } return n.default = e, t && t.set(e, n), n; }
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const TableRow = /*#__PURE__*/(0, _react.forwardRef)((props, ref) => {
  const {
    className,
    colors: colorsProp,
    header,
    ios,
    material,
    children,
    ...rest
  } = props;
  const elRef = (0, _react.useRef)(null);
  (0, _react.useImperativeHandle)(ref, () => ({
    el: elRef.current
  }));
  const themeClasses = (0, _useThemeClasses.useThemeClasses)({
    ios,
    material
  });
  const dark = (0, _useDarkClasses.useDarkClasses)();
  const colors = (0, _TableRowColors.TableRowColors)(colorsProp, dark);
  const c = themeClasses((0, _TableRowClasses.TableRowClasses)({
    ...props
  }, colors));
  const attrs = {
    ...rest
  };
  return /*#__PURE__*/_react.default.createElement("tr", _extends({
    className: c.base,
    ref: elRef
  }, attrs), children);
});
TableRow.displayName = 'TableRow';
var _default = exports.default = TableRow;

// svelte/components/TableRow.svelte
<script>
  import { TableRowClasses } from '../../shared/esm/classes/TableRowClasses.js';
  import { TableRowColors } from '../../shared/esm/colors/TableRowColors.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };

  export let ios = undefined;
  export let material = undefined;

  export let header = undefined;

  const rippleEl = { current: null };
  const dark = useDarkClasses();
  $: colors = TableRowColors(colorsProp, dark);

  $: c = useThemeClasses(
    { ios, material },
    TableRowClasses({ header }, colors),
    className,
    (v) => (c = v)
  );
</script>

<tr bind:this={rippleEl.current} class={c.base} {...$$restProps}>
  <slot />
</tr>
