// react/esm/components/Table.js
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
import React, { useRef, forwardRef, useImperativeHandle } from 'react';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { TableClasses } from '../../../shared/esm/classes/TableClasses.js';
const Table = /*#__PURE__*/forwardRef((props, ref) => {
  const {
    className,
    ios,
    material,
    children,
    ...rest
  } = props;
  const elRef = useRef(null);
  useImperativeHandle(ref, () => ({
    el: elRef.current
  }));
  const themeClasses = useThemeClasses({
    ios,
    material
  });
  const c = themeClasses(TableClasses({
    ...props
  }));
  const attrs = {
    ...rest
  };
  return /*#__PURE__*/React.createElement("table", _extends({
    className: c.base,
    ref: elRef
  }, attrs), children);
});
Table.displayName = 'Table';
export default Table;

// svelte/components/Table.svelte
<script>
  import { TableClasses } from '../../shared/esm/classes/TableClasses.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  let className = undefined;
  export { className as class };

  export let ios = undefined;
  export let material = undefined;

  const rippleEl = { current: null };

  $: c = useThemeClasses(
    { ios, material },
    TableClasses({}),
    className,
    (v) => (c = v)
  );
</script>

<table bind:this={rippleEl.current} class={c.base} {...$$restProps}>
  <slot />
</table>
