// react/esm/components/Checkbox.js
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
import React, { useEffect, useRef, forwardRef, useImperativeHandle } from 'react';
import { CheckboxClasses } from '../../../shared/esm/classes/CheckboxClasses.js';
import { CheckboxColors } from '../../../shared/esm/colors/CheckboxColors.js';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import { useTheme } from '../shared/use-theme.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { useTouchRipple } from '../shared/use-touch-ripple.js';
import CheckboxIcon from './icons/CheckboxIcon.js';
const Checkbox = /*#__PURE__*/forwardRef((props, ref) => {
  const {
    component = 'label',
    className,
    colors: colorsProp,
    defaultChecked,
    checked,
    indeterminate,
    name,
    value,
    disabled,
    readOnly,
    onChange,
    ios,
    material,
    touchRipple = true,
    // Children
    children,
    // Rest
    ...rest
  } = props;
  const inputElRef = useRef(null);
  const elRef = useRef(null);
  useImperativeHandle(ref, () => ({
    el: elRef.current,
    inputEl: inputElRef.current
  }));
  const Component = component;
  const attrs = {
    ...rest
  };
  const theme = useTheme({
    ios,
    material
  });
  const themeClasses = useThemeClasses({
    ios,
    material
  });
  const dark = useDarkClasses();
  useTouchRipple(elRef, theme === 'material' && touchRipple);
  const colors = CheckboxColors(colorsProp, dark);
  const state = checked || defaultChecked && !onChange || indeterminate ? 'checked' : 'notChecked';
  const c = themeClasses(CheckboxClasses(props, colors, className, dark), className);
  useEffect(() => {
    if (inputElRef.current) {
      inputElRef.current.indeterminate = !!indeterminate;
    }
  }, [indeterminate]);
  return /*#__PURE__*/React.createElement(Component, _extends({
    ref: elRef,
    className: c.base
  }, attrs), /*#__PURE__*/React.createElement("input", {
    ref: inputElRef,
    type: "checkbox",
    name: name,
    value: value,
    disabled: disabled,
    readOnly: readOnly,
    checked: checked,
    defaultChecked: defaultChecked,
    onChange: onChange,
    className: c.input
  }), /*#__PURE__*/React.createElement("i", {
    className: c.iconWrap[state]
  }, indeterminate ? /*#__PURE__*/React.createElement("span", {
    className: c.indeterminateIcon
  }) : /*#__PURE__*/React.createElement(CheckboxIcon, {
    ios: ios,
    material: material,
    className: c.icon[state]
  })), children);
});
Checkbox.displayName = 'Checkbox';
export default Checkbox;

// vue/components/Checkbox.vue
<template>
  <component :is="component" ref="elRef" :class="c.base">
    <input
      ref="inputElRef"
      type="checkbox"
      :name="name"
      :value="value"
      :disabled="disabled"
      :readonly="readonly"
      :checked="checked"
      :class="c.input"
      @change="onChange"
    />
    <i :class="c.iconWrap[state]">
      <span v-if="indeterminate" :class="c.indeterminateIcon" />
      <CheckboxIcon
        v-else
        :ios="ios"
        :material="material"
        :class="c.icon[state]"
      />
    </i>
    <slot />
  </component>
</template>
<script>
  import { computed, onMounted, ref, watch } from 'vue';
  import { useContext } from '../shared/use-context.js';

  import { CheckboxClasses } from '../../shared/esm/classes/CheckboxClasses.js';

  import { CheckboxColors } from '../../shared/esm/colors/CheckboxColors.js';

  import { darkClasses } from '../shared/use-dark-classes.js';

  import { themeClasses } from '../shared/use-theme-classes.js';

  import { useTouchRipple } from '../shared/use-touch-ripple.js';
  import CheckboxIcon from './icons/CheckboxIcon.vue';

  export default {
    name: 'k-checkbox',
    components: { CheckboxIcon },
    props: {
      component: {
        type: String,
        default: 'label',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      touchRipple: {
        type: Boolean,
        default: true,
      },
      checked: { type: Boolean, default: false },
      indeterminate: { type: Boolean, default: false },
      name: { type: String, default: undefined },
      value: { type: [Number, String], default: undefined },
      disabled: { type: Boolean, default: false },
      readonly: { type: Boolean, default: false },
    },
    emits: ['change'],
    setup(props, ctx) {
      const context = useContext();
      const useDarkClasses = darkClasses(context);
      const useThemeClasses = themeClasses(context);
      const elRef = ref(null);
      const inputElRef = ref(null);

      useTouchRipple(elRef, props, { context });

      const colors = computed(() =>
        CheckboxColors(props.colors || {}, useDarkClasses)
      );

      const state = computed(() =>
        props.checked || props.indeterminate ? 'checked' : 'notChecked'
      );

      const c = useThemeClasses(props, () =>
        CheckboxClasses(props, colors.value, ctx.attrs.class, useDarkClasses)
      );

      watch(
        () => props.indeterminate,
        (newValue) => {
          inputElRef.value.indeterminate = !!newValue;
        }
      );

      onMounted(() => {
        if (props.indeterminate)
          inputElRef.value.indeterminate = !!props.indeterminate;
      });

      const onChange = (e) => {
        ctx.emit('change', e);
      };

      return {
        elRef,
        inputElRef,
        c,
        state,
        onChange,
      };
    },
  };
</script>
