// svelte/components/Fab.svelte
<script>
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useTouchRipple } from '../shared/use-touch-ripple.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { FabClasses } from '../../shared/esm/classes/FabClasses.js';
  import { FabColors } from '../../shared/esm/colors/FabColors.js';
  import { printText } from '../shared/print-text.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let component = 'a'; // or 'button'

  export let href = undefined;
  export let text = undefined;
  export let textPosition = 'after';
  export let touchRipple = true;

  export let onClick = undefined;

  const rippleEl = { current: null };

  const dark = useDarkClasses();

  $: useTouchRipple(rippleEl, touchRipple);

  $: colors = FabColors(colorsProp, dark);

  $: c = useThemeClasses(
    { ios, material },
    FabClasses({}, colors),
    className,
    (v) => (c = v)
  );
</script>

{#if typeof component === 'string'}
  <svelte:element
    this={component}
    class={text ? c.base.withText : c.base.iconOnly}
    {href}
    bind:this={rippleEl.current}
    role="button"
    tabindex="0"
    on:click={onClick}
    {...$$restProps}
  >
    {#if (text || $$slots.text) && textPosition === 'before'}
      <span class={c.text}>{printText(text)}<slot name="text" /></span>
    {/if}
    {#if $$slots.icon}
      <span class={c.icon}><slot name="icon" /></span>
    {/if}
    {#if (text || $$slots.text) && textPosition === 'after'}
      <span class={c.text}>{printText(text)}<slot name="text" /></span>
    {/if}
    <slot />
  </svelte:element>
{:else}
  <svelte:component
    this={component}
    class={text ? c.base.withText : c.base.iconOnly}
    {href}
    bind:this={rippleEl.current}
    on:click={onClick}
    {...$$restProps}
  >
    {#if (text || $$slots.text) && textPosition === 'before'}
      <span class={c.text}>{printText(text)}<slot name="text" /></span>
    {/if}
    {#if $$slots.icon}
      <span class={c.icon}><slot name="icon" /></span>
    {/if}
    {#if (text || $$slots.text) && textPosition === 'after'}
      <span class={c.text}>{printText(text)}<slot name="text" /></span>
    {/if}
    <slot />
  </svelte:component>
{/if}

// vue/components/Fab.vue
<template>
  <component
    :is="component"
    ref="rippleElRef"
    :class="text || slots.text ? c.base.withText : c.base.iconOnly"
    role="button"
    tabindex="0"
    :href="href"
  >
    <span
      v-if="(text || slots.text) && textPosition === 'before'"
      :class="c.text"
      >{{ text }}<slot name="text"
    /></span>
    <span v-if="slots.icon" :class="c.icon"><slot name="icon" /></span>
    <span
      v-if="(text || slots.text) && textPosition === 'after'"
      :class="c.text"
      >{{ text }}<slot name="text"
    /></span>
    <slot />
  </component>
</template>
<script>
  import { computed, ref } from 'vue';
  import { useContext } from '../shared/use-context.js';

  import { FabClasses } from '../../shared/esm/classes/FabClasses.js';

  import { FabColors } from '../../shared/esm/colors/FabColors.js';

  import { themeClasses } from '../shared/use-theme-classes.js';

  import { useTouchRipple } from '../shared/use-touch-ripple.js';

  import { darkClasses } from '../shared/use-dark-classes.js';

  export default {
    name: 'k-fab',
    props: {
      component: {
        type: String,
        default: 'a',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      href: { type: [String, Boolean], default: undefined },
      text: { type: String, default: undefined },
      textPosition: { type: String, default: 'after' },
      touchRipple: { type: Boolean, default: true },
    },
    setup(props, ctx) {
      const context = useContext();
      const useDarkClasses = darkClasses(context);
      const useThemeClasses = themeClasses(context);
      const rippleElRef = ref(null);
      useTouchRipple(rippleElRef, props, { context });

      const colors = computed(() =>
        FabColors(props.colors || {}, useDarkClasses)
      );

      const c = useThemeClasses(props, () => FabClasses(props, colors.value));
      return {
        rippleElRef,
        slots: ctx.slots,
        c,
      };
    },
  };
</script>
