// svelte/components/ListItem.svelte
<script>
  import { cls } from '../../shared/esm/cls.js';
  import { useTheme } from '../shared/use-theme.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useTouchRipple } from '../shared/use-touch-ripple.js';
  import ChevronIcon from './icons/ChevronIcon.svelte';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { ListItemClasses } from '../../shared/esm/classes/ListItemClasses.js';
  import { ListItemColors } from '../../shared/esm/colors/ListItemColors.js';
  import { getReactiveContext } from '../shared/get-reactive-context.js';
  import { printText } from '../shared/print-text.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let component = 'li';
  export let mediaClass = '';
  export let innerClass = '';
  export let contentClass = '';
  export let titleWrapClass = '';

  export let titleFontSizeIos = 'text-[17px]';
  export let titleFontSizeMaterial = 'text-[16px]';

  export let withMedia = undefined;
  export let withTitle = undefined;

  // Content props
  export let title = '';
  export let subtitle = '';
  export let text = '';
  export let after = '';
  export let header = '';
  export let footer = '';

  export let menuListItem = false;
  export let menuListItemActive = false;

  export let groupTitle = false;

  // Title
  export let strongTitle = 'auto';

  // Label props
  export let label = false;

  // Link props
  export let chevron = undefined;
  export let chevronIos = true;
  export let chevronMaterial = true;
  export let href = undefined;
  export let target = undefined;
  export let dividers = undefined;
  export let contacts = false;

  export let link = false;
  export let linkComponent = 'a';
  export let linkProps = {};

  export let touchRipple = true;

  export let onClick = undefined;

  let ListDividersContext = getReactiveContext(
    'ListDividersContext',
    (value) => {
      ListDividersContext = value || {};
    }
  ) || { value: false };

  const rippleEl = { current: null };

  let theme;
  theme = useTheme({ ios, material }, (v) => (theme = v));

  const dark = useDarkClasses();

  $: hasChevron =
    typeof chevron === 'undefined'
      ? theme === 'ios'
        ? chevronIos
        : chevronMaterial
      : chevron;

  $: colors = ListItemColors(colorsProp, dark);

  $: isMenuListItemActive = menuListItem && menuListItemActive;

  $: textColor =
    colors[
      `${
        isMenuListItemActive
          ? 'menuListItemActiveText'
          : menuListItem
          ? 'menuListItemText'
          : 'text'
      }${theme === 'ios' ? 'Ios' : 'Material'}`
    ];

  $: isLink = !!href || href === '' || menuListItem || link;
  $: isLabel = !!label;

  $: needsTouchRipple =
    theme === 'material' && (isLabel || isLink) && touchRipple;

  $: useTouchRipple(rippleEl, needsTouchRipple);

  $: hrefComputed =
    href === true || href === false || typeof href === 'undefined'
      ? undefined
      : href || '';
  $: ItemContentComponent = isLink ? linkComponent : isLabel ? 'label' : 'div';
  $: linkPropsComputed = isLink
    ? { href: hrefComputed, target, ...linkProps }
    : {};

  $: isMediaItem =
    (title || $$slots.title) &&
    withTitle !== false &&
    (subtitle || text || $$slots.subtitle || $$slots.text);

  $: autoStrongTitle =
    strongTitle === 'auto' &&
    (title || $$slots.title) &&
    withTitle !== false &&
    (subtitle || text || $$slots.subtitle || $$slots.text);

  $: c = useThemeClasses(
    { ios, material },
    ListItemClasses(
      {
        menuListItem,
        dividers:
          typeof dividers === 'undefined'
            ? ListDividersContext.value
            : dividers,
        mediaClass,
        innerClass,
        contentClass,
        titleWrapClass,
        titleFontSizeIos,
        titleFontSizeMaterial,
        strongTitle,
        contacts: contacts === 'false' ? '' : contacts,
      },
      colors,
      {
        isMediaItem,
        theme,
        textColor,
        needsTouchRipple,
        isMenuListItemActive,
        darkClasses: dark,
        autoStrongTitle,
        className,
      }
    ),
    className,
    (v) => (c = v)
  );

  $: itemContentClasses =
    isLink || isLabel ? c.itemContent.link : c.itemContent.default;

  $: titleClasses = menuListItem
    ? c.title.menuListItem
    : strongTitle === true || autoStrongTitle
    ? c.title.strong
    : c.title.default;
</script>

{#if groupTitle}
  <svelte:element
    this={component}
    class={cls(c.groupTitle, className)}
    on:click={onClick}
  >
    {title}
    <slot name="title" />
    <slot />
  </svelte:element>
{:else}
  <svelte:element
    this={component}
    class={c.base}
    {...$$restProps}
    on:click={onClick}
  >
    {#if typeof ItemContentComponent === 'string'}
      <svelte:element
        this={ItemContentComponent}
        bind:this={rippleEl.current}
        class={itemContentClasses}
        {...linkPropsComputed}
      >
        {#if $$slots.media && withMedia !== false}
          <div class={c.media}><slot name="media" /></div>
        {/if}
        <div class={c.inner}>
          {#if header || $$slots.header}
            <div class={c.header}>
              {printText(header)}<slot name="header" />
            </div>
          {/if}
          {#if ((title || $$slots.title) && withTitle !== false) || after || $$slots.after}
            <div class={c.titleWrap}>
              {#if (title || $$slots.title) && withTitle !== false}
                <div class={titleClasses}>
                  {printText(title)}
                  <slot name="title" />
                </div>
              {/if}
              {#if after || $$slots.after}
                <div class={c.after}>
                  {printText(after)}
                  <slot name="after" />
                </div>
              {/if}
              {#if isLink && hasChevron && !menuListItem}
                <ChevronIcon class={c.chevron} />
              {/if}
            </div>
          {/if}
          {#if subtitle || $$slots.subtitle}
            <div class={c.subtitle}>
              {printText(subtitle)}<slot name="subtitle" />
            </div>
          {/if}
          {#if text || $$slots.text}
            <div class={c.text}>{printText(text)}<slot name="text" /></div>
          {/if}
          {#if footer || $$slots.footer}
            <div class={c.footer}>
              {printText(footer)}<slot name="footer" />
            </div>
          {/if}
          <slot name="inner" />
        </div>
        <slot name="content" />
      </svelte:element>
    {:else}
      <svelte:component
        this={ItemContentComponent}
        bind:this={rippleEl.current}
        class={itemContentClasses}
        {...linkPropsComputed}
      >
        {#if $$slots.media}
          <div class={c.media}><slot name="media" /></div>
        {/if}
        <div class={c.inner}>
          {#if header || $$slots.header}
            <div class={c.header}>
              {printText(header)}<slot name="header" />
            </div>
          {/if}
          {#if ((title || $$slots.title) && withTitle !== false) || after || $$slots.after}
            <div class={c.titleWrap}>
              {#if (title || $$slots.title) && withTitle !== false}
                <div class={titleClasses}>
                  {printText(title)}
                  <slot name="title" />
                </div>
              {/if}
              {#if after || $$slots.after}
                <div class={c.after}>
                  {printText(after)}
                  <slot name="after" />
                </div>
              {/if}
              {#if isLink && hasChevron && !menuListItem}
                <ChevronIcon class={c.chevron} />
              {/if}
            </div>
          {/if}
          {#if subtitle || $$slots.subtitle}
            <div class={c.subtitle}>
              {printText(subtitle)}<slot name="subtitle" />
            </div>
          {/if}
          {#if text || $$slots.text}
            <div class={c.text}>{printText(text)}<slot name="text" /></div>
          {/if}
          {#if footer || $$slots.footer}
            <div class={c.footer}>
              {printText(footer)}<slot name="footer" />
            </div>
          {/if}
          <slot name="inner" />
        </div>
        <slot name="content" />
      </svelte:component>
    {/if}
    <slot />
  </svelte:element>
{/if}

// vue/components/ListItem.vue
<template>
  <component :is="component" v-if="groupTitle" :class="c.groupTitle">
    {{ title }}
    <slot name="title" />
    <slot />
  </component>
  <component :is="component" v-else :class="c.base">
    <component
      :is="ItemContentComponent"
      ref="rippleElRef"
      :class="itemContentClasses"
      v-bind="linkPropsComputed"
    >
      <div v-if="media || slots.media" :class="c.media">
        {{ media }}<slot name="media" />
      </div>
      <div :class="c.inner">
        <div v-if="header || slots.header" :class="c.header">
          {{ header }}<slot name="header" />
        </div>
        <div
          v-if="title || after || slots.title || slots.after"
          :class="c.titleWrap"
        >
          <div v-if="title || slots.title" :class="titleClasses">
            {{ title }}<slot name="title" />
          </div>
          <div v-if="after || slots.after" :class="c.after">
            {{ after }}<slot name="after" />
          </div>
          <chevron-icon
            v-if="isLink && hasChevron && !menuListItem"
            :class="c.chevron"
          />
        </div>
        <div v-if="subtitle || slots.subtitle" :class="c.subtitle">
          {{ subtitle }}<slot name="subtitle" />
        </div>
        <div v-if="text || slots.text" :class="c.text">
          {{ text }}<slot name="text" />
        </div>
        <div v-if="footer || slots.footer" :class="c.footer">
          {{ footer }}<slot name="footer" />
        </div>
        <slot name="inner" />
      </div>
      <slot name="content" />
    </component>
    <slot />
  </component>
</template>
<script>
  import { computed, inject, ref } from 'vue';
  import { useContext } from '../shared/use-context.js';

  import { useTheme } from '../shared/use-theme.js';

  import { themeClasses } from '../shared/use-theme-classes.js';

  import { useTouchRipple } from '../shared/use-touch-ripple.js';
  import ChevronIcon from './icons/ChevronIcon.vue';

  import { darkClasses } from '../shared/use-dark-classes.js';

  import { ListItemClasses } from '../../shared/esm/classes/ListItemClasses.js';

  import { ListItemColors } from '../../shared/esm/colors/ListItemColors.js';

  export default {
    name: 'k-list-item',
    components: {
      ChevronIcon,
    },
    props: {
      component: {
        type: String,
        default: 'li',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      mediaClass: { type: String, default: '' },
      innerClass: { type: String, default: '' },
      contentClass: { type: String, default: '' },
      titleWrapClass: { type: String, default: '' },
      titleFontSizeIos: { type: String, default: 'text-[17px]' },
      titleFontSizeMaterial: {
        type: String,
        default: 'text-[16px]',
      },

      dividers: {
        type: Boolean,
        default: undefined,
      },
      contacts: {
        type: Boolean,
        default: undefined,
      },

      // Content props
      title: { type: String, default: undefined },
      subtitle: { type: String, default: undefined },
      text: { type: String, default: undefined },
      after: { type: String, default: undefined },
      media: { type: String, default: undefined },
      header: { type: String, default: undefined },
      footer: { type: String, default: undefined },

      menuListItem: { type: Boolean, default: false },
      menuListItemActive: { type: Boolean, default: false },

      groupTitle: { type: Boolean, default: false },

      // Title
      strongTitle: { type: [String, Boolean], default: 'auto' },

      // Label props
      label: { type: Boolean, default: false },

      // Link props
      chevron: { type: Boolean, default: undefined },
      chevronIos: { type: Boolean, default: true },
      chevronMaterial: { type: Boolean, default: true },
      href: { type: [Boolean, String], default: undefined },
      target: { type: String, default: undefined },

      link: { type: Boolean, default: undefined },
      linkComponent: { type: String, default: 'a' },
      linkProps: { type: Object, default: () => ({}) },

      touchRipple: { type: Boolean, default: true },
    },
    setup(props, ctx) {
      const context = useContext();
      const useDarkClasses = darkClasses(context);
      const useThemeClasses = themeClasses(context);
      const rippleElRef = ref(null);
      const theme = useTheme(props, context);

      const colors = computed(() =>
        ListItemColors(props.colors || {}, useDarkClasses)
      );

      const isMenuListItemActive = computed(
        () => props.menuListItem && props.menuListItemActive
      );

      const hasChevron = computed(() =>
        typeof props.chevron === 'undefined'
          ? theme.value === 'ios'
            ? props.chevronIos
            : props.chevronMaterial
          : props.chevron
      );

      const textColor = computed(
        () =>
          colors.value[
            `${
              isMenuListItemActive.value
                ? 'menuListItemActiveText'
                : props.menuListItem
                ? 'menuListItemText'
                : 'text'
            }${theme.value === 'ios' ? 'Ios' : 'Material'}`
          ]
      );

      const isLink = computed(
        () =>
          !!props.href || props.href === '' || props.menuListItem || props.link
      );
      const isLabel = computed(() => !!props.label);

      const needsTouchRipple = computed(
        () =>
          theme.value === 'material' &&
          (isLabel.value || isLink.value) &&
          props.touchRipple
      );
      useTouchRipple(rippleElRef, props, {
        addCondition: () => isLabel.value || isLink.value,
        context,
      });

      const hrefComputed = computed(() =>
        props.href === true ||
        props.href === false ||
        typeof props.href === 'undefined'
          ? undefined
          : props.href || ''
      );
      const ItemContentComponent = computed(() =>
        isLink.value ? props.linkComponent : isLabel.value ? 'label' : 'div'
      );
      const linkPropsComputed = computed(() =>
        isLink.value
          ? {
              href: hrefComputed.value,
              target: props.target,
              ...(props.linkProps || {}),
            }
          : {}
      );

      const isMediaItem = computed(
        () =>
          (props.title || ctx.slots.title) &&
          (props.subtitle || ctx.slots.subtitle || props.text || ctx.slots.text)
      );

      const autoStrongTitle = computed(
        () => props.strongTitle === 'auto' && isMediaItem.value
      );

      const ListDividersContext = inject('ListDividersContext', {
        value: false,
      });

      const c = useThemeClasses(props, () =>
        ListItemClasses(
          {
            ...props,
            dividers:
              typeof props.dividers === 'undefined'
                ? ListDividersContext.value
                : props.dividers,
            contacts:
              typeof props.contacts === 'undefined' ? '' : props.contacts,
          },
          colors.value,
          {
            isMediaItem: isMediaItem.value,
            theme: theme.value,
            textColor: textColor.value,
            needsTouchRipple: needsTouchRipple.value,
            isMenuListItemActive: isMenuListItemActive.value,
            darkClasses: useDarkClasses,
            autoStrongTitle: autoStrongTitle.value,
            className: ctx.attrs.class,
          }
        )
      );

      const itemContentClasses = computed(() =>
        isLink.value || isLabel.value
          ? c.value.itemContent.link
          : c.value.itemContent.default
      );

      const titleClasses = computed(() =>
        props.menuListItem
          ? c.value.title.menuListItem
          : props.strongTitle === true || autoStrongTitle.value
          ? c.value.title.strong
          : c.value.title.default
      );

      return {
        rippleElRef,
        ItemContentComponent,
        isLink,
        c,
        hasChevron,
        linkPropsComputed,
        itemContentClasses,
        titleClasses,
        slots: ctx.slots,
      };
    },
  };
</script>
