// react/esm/components/ListButton.js
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
import React, { useRef, forwardRef, useImperativeHandle } from 'react';
import { useTheme } from '../shared/use-theme.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import { useTouchRipple } from '../shared/use-touch-ripple.js';
import { ListButtonClasses } from '../../../shared/esm/classes/ListButtonClasses.js';
import { ListButtonColors } from '../../../shared/esm/colors/ListButtonColors.js';
import { useListDividers } from '../shared/use-list-dividers.js';
const ListButton = /*#__PURE__*/forwardRef((props, ref) => {
  const {
    component = 'li',
    className,
    colors: colorsProp,
    // Link props
    href,
    target,
    // Button props
    type,
    value,
    linkComponent = 'a',
    linkProps = {},
    ios,
    material,
    touchRipple = true,
    // Children
    children,
    // Rest
    ...rest
  } = props;
  const elRef = useRef(null);
  const rippleElRef = useRef(null);
  const dividers = useListDividers();
  useImperativeHandle(ref, () => ({
    el: elRef.current
  }));
  const Component = component;
  const attrs = {
    ...rest
  };
  const theme = useTheme({
    ios,
    material
  });
  const themeClasses = useThemeClasses({
    ios,
    material
  });
  useTouchRipple(rippleElRef, theme === 'material' && touchRipple);
  const dark = useDarkClasses();
  const colors = ListButtonColors(colorsProp, dark);
  const c = themeClasses(ListButtonClasses({
    ...props,
    dividers
  }, colors, className, theme), className);
  const isLink = !!href || href === '';
  const hrefComputed = !isLink || href === true || href === false ? undefined : href || '';
  const buttonAttrs = {
    href: hrefComputed,
    target,
    type,
    value,
    ...linkProps
  };
  const ButtonComponent = isLink ? linkComponent : 'button';
  return /*#__PURE__*/React.createElement(Component, _extends({
    ref: elRef,
    className: c.base
  }, attrs), /*#__PURE__*/React.createElement(ButtonComponent, _extends({
    ref: rippleElRef,
    className: c.button
  }, buttonAttrs), children));
});
ListButton.displayName = 'ListButton';
export default ListButton;

// vue/components/ListButton.vue
<template>
  <component :is="component" :class="c.base">
    <component
      :is="ButtonComponent"
      ref="rippleElRef"
      :class="c.button"
      v-bind="buttonAttrs"
    >
      <slot />
    </component>
  </component>
</template>
<script>
  import { computed, inject, ref } from 'vue';
  import { useContext } from '../shared/use-context.js';

  import { ListButtonClasses } from '../../shared/esm/classes/ListButtonClasses.js';

  import { ListButtonColors } from '../../shared/esm/colors/ListButtonColors.js';

  import { useTheme } from '../shared/use-theme.js';

  import { themeClasses } from '../shared/use-theme-classes.js';

  import { darkClasses } from '../shared/use-dark-classes.js';

  import { useTouchRipple } from '../shared/use-touch-ripple.js';

  export default {
    name: 'k-list-button',
    props: {
      component: {
        type: String,
        default: 'li',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },

      // Link props
      href: { type: [String, Boolean], default: undefined },
      target: { type: String, default: undefined },

      // Button props
      type: { type: String, default: undefined },
      value: { type: [String, Number], default: undefined },

      linkComponent: { type: String, default: 'a' },
      linkProps: { type: Object, default: () => ({}) },

      touchRipple: { type: Boolean, default: true },
    },
    setup(props, ctx) {
      const context = useContext();
      const useDarkClasses = darkClasses(context);
      const useThemeClasses = themeClasses(context);
      const rippleElRef = ref(null);
      useTouchRipple(rippleElRef, props, { context });

      const ListDividersContext = inject('ListDividersContext', {
        value: false,
      });

      const colors = computed(() =>
        ListButtonColors(props.colors || {}, useDarkClasses)
      );

      const theme = useTheme(props, context);

      const c = useThemeClasses(props, () =>
        ListButtonClasses(
          { ...props, dividers: ListDividersContext.value },
          colors.value,
          ctx.attrs.class,
          theme.value
        )
      );

      const isLink = computed(() => !!props.href || props.href === '');
      const hrefComputed = computed(() =>
        !isLink.value || props.href === true || props.href === false
          ? undefined
          : props.href || ''
      );
      const buttonAttrs = computed(() => ({
        href: hrefComputed.value,
        target: props.target,
        type: props.type,
        value: props.value,
        ...(props.linkProps || {}),
      }));

      const ButtonComponent = computed(() =>
        isLink.value ? props.linkComponent : 'button'
      );
      return {
        rippleElRef,
        c,
        buttonAttrs,
        ButtonComponent,
      };
    },
  };
</script>
