// svelte/components/ListInput.svelte
<script>
  import { useTheme } from '../shared/use-theme.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import DeleteIcon from './icons/DeleteIcon.svelte';
  import DropdownIcon from './icons/DropdownIcon.svelte';
  import ListItem from './ListItem.svelte';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { ListInputClasses } from '../../shared/esm/classes/ListInputClasses.js';
  import { ListInputColors } from '../../shared/esm/colors/ListInputColors.js';
  import { cls } from '../../shared/esm/cls.js';
  import { printText } from '../shared/print-text.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let component = 'li';

  export let label = '';
  export let outline = undefined;
  export let outlineIos = undefined;
  export let outlineMaterial = undefined;
  export let floatingLabel = false;
  export let info = undefined; // string
  export let error = undefined; // string or bool
  export let clearButton = false;
  export let dropdown = false;

  // input props
  export let inputId = undefined;
  export let inputStyle = undefined;
  export let inputClass = '';

  export let name = undefined;
  export let value = undefined;
  export let type = 'text';
  export let inputmode = undefined;
  export let readonly = undefined;
  export let required = undefined;
  export let disabled = undefined;
  export let placeholder = undefined;
  export let size = undefined;
  export let accept = undefined;
  export let autocomplete = undefined;
  export let autocorrect = undefined;
  export let autocapitalize = undefined;
  export let spellcheck = undefined;
  export let autofocus = undefined;
  export let autosave = undefined;
  export let max = undefined;
  export let min = undefined;
  export let step = undefined;
  export let maxlength = undefined;
  export let minlength = undefined;
  export let multiple = undefined;
  export let pattern = undefined;
  export let tabindex = undefined;

  export let onInput = undefined;
  export let onChange = undefined;
  export let onFocus = undefined;
  export let onBlur = undefined;
  export let onClear = undefined;

  let theme;
  theme = useTheme({ ios, material }, (v) => (theme = v));

  $: isOutline =
    typeof outline === 'undefined'
      ? theme === 'ios'
        ? outlineIos
        : outlineMaterial
      : outline;

  let inputEl = null;

  let isFocused = false;

  const dark = useDarkClasses();

  $: colors = ListInputColors(colorsProp, dark);

  $: labelStyle = label && floatingLabel ? 'floating' : 'stacked';
  $: labelStyleIsFloating =
    labelStyle === 'floating' ? 'floating' : 'notFloating';

  const getDomValue = () => {
    if (!inputEl) return undefined;
    return inputEl.value;
  };

  const isInputHasValue = () => {
    const domValue = getDomValue();
    return typeof value === 'undefined'
      ? domValue || domValue === 0
      : value || value === 0;
  };
  $: isFloatingTransformed =
    (label || $$slots.label) &&
    floatingLabel &&
    !isInputHasValue() &&
    !isFocused;

  const getLabelColor = () => {
    if (error || $$slots.error) return colors.errorText;
    if (theme === 'material') {
      return isFocused
        ? colors.labelTextFocusMaterial
        : colors.labelTextMaterial;
    }
    if (theme === 'ios') {
      return isFocused ? colors.labelTextFocusIos : colors.labelTextIos;
    }

    return '';
  };

  const onFocusInternal = (e) => {
    isFocused = true;
    if (onFocus) onFocus(e);
  };
  const onBlurInternal = (e) => {
    isFocused = false;
    if (onBlur) onBlur(e);
  };

  $: c = useThemeClasses(
    { ios, material },
    ListInputClasses(
      {
        error,
        type,
        inputClass,
        outline: isOutline,
      },
      colors,
      {
        isFloatingTransformed,
        isFocused,
        darkClasses: dark,
        getLabelColor,
        inputClass,
        hasLabel: !!label || $$slots.label,
      }
    ),
    className,
    (v) => (c = v)
  );

  $: InputComponent = type === 'select' || type === 'textarea' ? type : 'input';
  $: needsType = InputComponent === 'input';
</script>

<ListItem
  {component}
  class={c.base}
  title={undefined}
  mediaClass={c.media}
  innerClass={c.inner[labelStyle]}
  contentClass={c.itemContent}
  titleWrapClass={c.titleWrap}
  withMedia={!!$$slots.media}
  withTitle={!!$$slots.label || !!label}
  dividers={theme === 'material' || isOutline ? false : undefined}
  {...$$restProps}
>
  <svelte:fragment slot="content">
    {#if isOutline || theme === 'material'}
      <span class={c.border} />
    {/if}
  </svelte:fragment>
  <svelte:fragment slot="media">
    {#if $$slots.media}
      <slot name="media" />
    {/if}
  </svelte:fragment>

  <svelte:fragment slot="inner">
    {#if label || $$slots.label}
      <div class={c.label[labelStyle]}>
        <div class={c.labelText}>
          {printText(label)}
          <slot name="label" />
        </div>
      </div>
    {/if}
    <div class={c.inputWrap[labelStyle]}>
      {#if $$slots.input}
        <slot name="input" />
      {:else}
        <!-- svelte-ignore a11y-autofocus -->
        {#if type === 'select'}
          <svelte:element
            this={InputComponent}
            id={inputId}
            bind:this={inputEl}
            class={c.input[labelStyleIsFloating]}
            style={inputStyle}
            {name}
            type={needsType ? type : undefined}
            {placeholder}
            {inputmode}
            {size}
            {accept}
            {autocomplete}
            {autocorrect}
            {autocapitalize}
            {spellcheck}
            {autofocus}
            {autosave}
            {disabled}
            {max}
            {maxlength}
            {min}
            {minlength}
            {step}
            {multiple}
            {readonly}
            {required}
            {pattern}
            {tabindex}
            {value}
            on:input={onInput}
            on:change={onChange}
            on:focus={onFocusInternal}
            on:blur={onBlurInternal}
          >
            <slot />
          </svelte:element>
        {:else}
          <svelte:element
            this={InputComponent}
            id={inputId}
            bind:this={inputEl}
            class={c.input[labelStyleIsFloating]}
            style={inputStyle}
            {name}
            type={needsType ? type : undefined}
            {placeholder}
            {inputmode}
            {size}
            {accept}
            {autocomplete}
            {autocorrect}
            {autocapitalize}
            {spellcheck}
            {autofocus}
            {autosave}
            {disabled}
            {max}
            {maxlength}
            {min}
            {minlength}
            {step}
            {multiple}
            {readonly}
            {required}
            {pattern}
            {tabindex}
            {value}
            on:input={onInput}
            on:change={onChange}
            on:focus={onFocusInternal}
            on:blur={onBlurInternal}
          />
        {/if}
      {/if}

      {#if clearButton}
        <DeleteIcon {theme} onClick={onClear} class={c.clearButton} />
      {/if}
      {#if dropdown}
        <DropdownIcon class={c.dropdown} />
      {/if}
    </div>
    <!-- error info content -->
    {#if (error && error !== true) || $$slots.error}
      <div class={cls(c.errorInfo, c.error)}>
        {#if error !== true}{error}{/if}
        <slot name="error" />
      </div>
    {/if}
    {#if (info || $$slots.info) && !error}
      <div class={cls(c.errorInfo, c.info)}>
        {info}
        <slot name="info" />
      </div>
    {/if}
    <!-- error info end -->
  </svelte:fragment>

  {#if type !== 'select'}
    <slot />
  {/if}
</ListItem>

// vue/components/ListInput.vue
<template>
  <k-list-item
    :component="component"
    :class="c.base"
    :title="null"
    :media-class="c.media"
    :inner-class="c.inner[labelStyle]"
    :content-class="c.itemContent"
    :title-wrap-class="c.titleWrap"
    :dividers="theme === 'material' || isOutline ? false : undefined"
  >
    <template v-if="isOutline || theme === 'material'" #content>
      <span :class="c.border" />
    </template>
    <template v-if="slots.media" #media>
      <slot name="media" />
    </template>
    <template #inner>
      <div v-if="label" :class="c.label[labelStyle]">
        <div :class="c.labelText">{{ label }}<slot name="label" /></div>
      </div>
      <div :class="c.inputWrap[labelStyle]">
        <component
          :is="InputComponent"
          v-if="!slots.input"
          :id="inputId"
          ref="inputElRef"
          :class="c.input[labelStyleIsFloating]"
          :style="inputStyle"
          :name="name"
          :placeholder="placeholder"
          :inputmode="inputmode"
          :accept="accept"
          :autocomplete="autocomplete"
          :autocorrect="autocorrect"
          :autocapitalize="autocapitalize"
          :spellcheck="spellcheck"
          :autofocus="autofocus"
          :autosave="autosave"
          :disabled="disabled"
          :max="max"
          :maxlength="maxlength"
          :min="min"
          :minlength="minlength"
          :step="step"
          :multiple="multiple"
          :readonly="readonly"
          :required="required"
          :pattern="pattern"
          :tabindex="tabindex"
          v-bind="inputProps"
          @input="onInput"
          @change="onChange"
          @focus="onFocusInternal"
          @blur="onBlurInternal"
        >
          <slot v-if="type === 'select'" />
        </component>
        <slot v-if="slots.input" name="input" />
        <DeleteIcon
          v-if="clearButton"
          :theme="theme"
          :class="c.clearButton"
          @click="onClear"
        />
        <DropdownIcon v-if="dropdown" :class="c.dropdown" />
      </div>
      <!-- error info content -->
      <div
        v-if="(error && error !== true) || slots.error"
        :class="cls(c.errorInfo, c.error)"
      >
        {{ error }}<slot name="error" />
      </div>
      <div
        v-if="(info && !error) || slots.info"
        :class="cls(c.errorInfo, c.info)"
      >
        {{ info }}<slot name="info" />
      </div>
    </template>
    <slot v-if="type !== 'select'" />
  </k-list-item>
</template>
<script>
  import { computed, ref } from 'vue';
  import { useContext } from '../shared/use-context.js';

  import { cls } from '../../shared/esm/cls.js';

  import { useTheme } from '../shared/use-theme.js';

  import { themeClasses } from '../shared/use-theme-classes.js';

  import DeleteIcon from './icons/DeleteIcon.vue';
  import DropdownIcon from './icons/DropdownIcon.vue';
  import kListItem from './ListItem.vue';

  import { darkClasses } from '../shared/use-dark-classes.js';

  import { ListInputClasses } from '../../shared/esm/classes/ListInputClasses.js';

  import { ListInputColors } from '../../shared/esm/colors/ListInputColors.js';

  export default {
    name: 'k-list-input',
    components: {
      DeleteIcon,
      DropdownIcon,
      kListItem,
    },
    props: {
      component: {
        type: String,
        default: 'li',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      outline: {
        type: Boolean,
        default: undefined,
      },
      outlineIos: {
        type: Boolean,
        default: undefined,
      },
      outlineMaterial: {
        type: Boolean,
        default: undefined,
      },
      label: String,
      floatingLabel: Boolean,
      info: String, // string
      error: String, // string or bool
      clearButton: Boolean,
      dropdown: Boolean,

      // input props
      inputId: String,
      inputStyle: [String, Object],
      inputClass: { type: String, default: '' },

      name: String,
      value: [String, Number],
      type: { type: String, default: 'text' },
      inputmode: String,
      readonly: Boolean,
      required: Boolean,
      disabled: Boolean,
      placeholder: String,
      size: { type: [String, Number], default: undefined },
      accept: [String, Number],
      autocomplete: [String],
      autocorrect: [String],
      autocapitalize: [String],
      spellcheck: [String],
      autofocus: Boolean,
      autosave: String,
      max: [String, Number],
      min: [String, Number],
      step: [String, Number],
      maxlength: [String, Number],
      minlength: [String, Number],
      multiple: Boolean,
      pattern: String,
      tabindex: [String, Number],
    },
    emits: ['change', 'input', 'focus', 'blur', 'clear'],
    setup(props, ctx) {
      const context = useContext();
      const useDarkClasses = darkClasses(context);
      const useThemeClasses = themeClasses(context);
      const inputElRef = ref(null);
      const isFocused = ref(false);
      const theme = useTheme(props, context);
      const isOutline = computed(() =>
        typeof props.outline === 'undefined'
          ? theme.value === 'ios'
            ? props.outlineIos
            : props.outlineMaterial
          : props.outline
      );

      const labelStyle = computed(() =>
        props.label && props.floatingLabel ? 'floating' : 'stacked'
      );

      const labelStyleIsFloating = computed(() =>
        labelStyle.value === 'floating' ? 'floating' : 'notFloating'
      );

      const colors = computed(() =>
        ListInputColors(props.colors || {}, useDarkClasses)
      );

      const getDomValue = () => {
        if (!inputElRef.value) return undefined;
        return inputElRef.value.value;
      };

      const isInputHasValue = () => {
        const domValue = getDomValue();
        return typeof props.value === 'undefined'
          ? domValue || domValue === 0
          : props.value || props.value === 0;
      };
      const isFloatingTransformed = computed(() => {
        return (
          props.label &&
          props.floatingLabel &&
          !isInputHasValue() &&
          !isFocused.value
        );
      });

      const getLabelColor = () => {
        if (props.error) return colors.value.errorText;
        if (theme === 'material') {
          return isFocused.value
            ? colors.value.labelTextFocusMaterial
            : colors.value.labelTextMaterial;
        }
        if (theme === 'ios') {
          return isFocused.value
            ? colors.value.labelTextFocusIos
            : colors.value.labelTextIos;
        }

        return '';
      };

      const onChange = (e) => {
        ctx.emit('change', e);
      };

      const onInput = (e) => {
        ctx.emit('input', e);
      };

      const onClear = (e) => {
        ctx.emit('clear', e);
      };

      const onFocusInternal = (e) => {
        isFocused.value = true;
        ctx.emit('focus', e);
      };
      const onBlurInternal = (e) => {
        isFocused.value = false;
        ctx.emit('blur', e);
      };

      const c = useThemeClasses(props, () =>
        ListInputClasses({ ...props }, colors.value, {
          isFloatingTransformed: isFloatingTransformed.value,
          isFocused: isFocused.value,
          darkClasses: useDarkClasses,
          getLabelColor,
          outline: isOutline,
          hasLabel: props.label || ctx.slots.label,
        })
      );

      const InputComponent = computed(() =>
        props.type === 'select' || props.type === 'textarea'
          ? props.type
          : 'input'
      );
      const needsType = computed(() => InputComponent.value === 'input');

      const inputProps = computed(() => {
        return {
          ...(typeof props.size === 'undefined' ? {} : { size: props.size }),
          ...(needsType.value ? { type: props.type } : {}),
          ...(typeof props.value === 'undefined' ? {} : { value: props.value }),
        };
      });

      return {
        inputElRef,
        onChange,
        onInput,
        onFocusInternal,
        onBlurInternal,
        onClear,
        c,
        InputComponent,
        needsType,
        cls,
        labelStyle,
        labelStyleIsFloating,
        slots: ctx.slots,
        inputProps,
        theme,
        isOutline,
      };
    },
  };
</script>
