// svelte/components/Messagebar.svelte
<script>
  import { MessagebarClasses } from '../../shared/esm/classes/MessagebarClasses.js';
  import { MessagebarColors } from '../../shared/esm/colors/MessagebarColors.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import Toolbar from './Toolbar.svelte';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let component = 'div';
  export let id = undefined;
  export let name = undefined;
  export let placeholder = 'Message';
  export let value = undefined;
  export let outline = false;
  export let leftClass = '';
  export let rightClass = '';
  export let style = undefined;
  export let textareaId = undefined;
  export let disabled = undefined;
  export let size = undefined;

  export let onInput = undefined;
  export let onChange = undefined;
  export let onFocus = undefined;

  const rippleEl = { current: null };
  let areaEl = null;
  let isFocused = false;

  const dark = useDarkClasses();

  $: colors = MessagebarColors(colorsProp, dark);

  const onFocusInternal = (e) => {
    isFocused = true;
    if (onFocus) onFocus(e);
  };

  $: c = useThemeClasses(
    { ios, material },
    MessagebarClasses(
      {
        leftClass,
        rightClass,
      },
      colors,
      { isFocused }
    ),
    className,
    (v) => (c = v)
  );
</script>

<svelte:element
  this={component}
  {id}
  {style}
  bind:this={rippleEl.current}
  class={c.base}
  {...$$restProps}
>
  <Toolbar {colors} {outline}>
    {#if $$slots.left}
      <div class={c.left}><slot name="left" /></div>
    {/if}
    <div class={c.messagebarArea}>
      <textarea
        id={textareaId}
        bind:this={areaEl}
        type="textarea"
        class={c.messagebarInput}
        {placeholder}
        {name}
        {value}
        {size}
        {disabled}
        on:input={onInput}
        on:change={onChange}
        on:focus={onFocusInternal}
      />
    </div>
    {#if $$slots.right}
      <div class={c.right}><slot name="right" /></div>
    {/if}
  </Toolbar>
</svelte:element>

// vue/components/Messagebar.vue
<template>
  <component :is="component" :id="id" ref="elRef" :class="c.base">
    <k-toolbar :outline="outline" :colors="colors">
      <div v-if="slots.left" :class="c.left"><slot name="left" /></div>
      <div :class="c.messagebarArea">
        <textarea
          id="textareaId"
          ref="areaElRef"
          type="textarea"
          :class="c.messagebarInput"
          :placeholder="placeholder"
          :name="name"
          :value="value"
          :disabled="disabled"
          :size="size"
          @input="onInput"
          @change="onChange"
          @focus="onFocusInternal"
        />
      </div>
      <div v-if="slots.right" :class="c.right"><slot name="right" /></div>
    </k-toolbar>
  </component>
</template>
<script>
  import { ref, computed } from 'vue';
  import { useContext } from '../shared/use-context.js';

  import { MessagebarClasses } from '../../shared/esm/classes/MessagebarClasses.js';

  import { MessagebarColors } from '../../shared/esm/colors/MessagebarColors.js';

  import { darkClasses } from '../shared/use-dark-classes.js';

  import { themeClasses } from '../shared/use-theme-classes.js';
  import kToolbar from './Toolbar.vue';

  export default {
    name: 'k-messagebar',
    components: {
      kToolbar,
    },
    props: {
      component: {
        type: String,
        default: 'div',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      id: String,
      name: { type: String, default: undefined },
      value: { type: [Number, String], default: undefined },
      placeholder: { type: String, defaullt: 'Message' },
      outline: { type: Boolean, default: false },
      rightClass: { type: String, default: '' },
      leftClass: { type: String, default: '' },
      disabled: { type: Boolean, default: undefined },
      textareaId: String,
      size: { type: [Number, String], default: undefined },
    },
    emits: ['change', 'input', 'focus'],
    setup(props, ctx) {
      const context = useContext();
      const useDarkClasses = darkClasses(context);
      const useThemeClasses = themeClasses(context);
      const elRef = ref(null);
      const areaElRef = ref(null);
      const isFocused = ref(false);

      const colors = computed(() =>
        MessagebarColors(props.colors || {}, useDarkClasses)
      );

      const onFocusInternal = (e) => {
        isFocused.value = true;
        ctx.emit('focus', e);
      };

      const c = useThemeClasses(props, () =>
        MessagebarClasses(
          {
            ...props,
          },
          colors.value,
          { isFocused }
        )
      );

      const onChange = (e) => {
        ctx.emit('change', e);
      };

      const onInput = (e) => {
        ctx.emit('input', e);
      };

      return {
        elRef,
        areaElRef,
        c,
        onChange,
        onInput,
        onFocusInternal,
        slots: ctx.slots,
      };
    },
  };
</script>
