// react/esm/components/Popover.js
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
/* eslint-disable no-restricted-globals */
import React, { useEffect, useRef, useState, forwardRef, useImperativeHandle } from 'react';
import { cls } from '../../../shared/esm/cls.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { useTheme } from '../shared/use-theme.js';
import { calcPopoverPosition } from '../../../shared/esm/calc-popover-position.js';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import { PopoverClasses } from '../../../shared/esm/classes/PopoverClasses.js';
import { PopoverColors } from '../../../shared/esm/colors/PopoverColors.js';
const Popover = /*#__PURE__*/forwardRef((props, ref) => {
  const {
    component = 'div',
    className,
    angle = true,
    angleClassName = '',
    colors: colorsProp,
    size = 'w-64',
    opened,
    backdrop = true,
    onBackdropClick,
    target,
    targetX,
    targetY,
    targetWidth,
    targetHeight,
    translucent = true,
    ios,
    material,
    // Children
    children,
    // Rest
    style = {},
    ...rest
  } = props;
  const elRef = useRef(null);
  const angleElRef = useRef(null);
  const [positions, setPositions] = useState({
    set: false,
    angleTop: 0,
    angleLeft: 0,
    anglePosition: 'bottom',
    popoverTop: 0,
    popoverLeft: 0,
    popoverPosition: 'top-left'
  });
  useImperativeHandle(ref, () => ({
    el: elRef.current
  }));
  const state = opened ? 'opened' : 'closed';
  const Component = component;
  const attrs = {
    ...rest
  };
  const theme = useTheme({
    ios,
    material
  });
  const themeClasses = useThemeClasses({
    ios,
    material
  });
  const dark = useDarkClasses();
  const colors = PopoverColors(colorsProp, dark);
  const c = themeClasses(PopoverClasses({
    ...props,
    size,
    angleClassName,
    translucent
  }, colors, className), className);
  const setPopover = () => {
    if (!target || !elRef.current || !opened) return;
    setPositions(calcPopoverPosition({
      popoverEl: elRef.current,
      targetEl: target,
      angleEl: angleElRef.current,
      needsAngle: angle,
      targetX,
      targetY,
      targetHeight,
      targetWidth,
      theme
    }));
  };
  const attachEvents = () => {
    if (typeof window === 'undefined') return;
    window.addEventListener('resize', setPopover);
  };
  const detachEvents = () => {
    if (typeof window === 'undefined') return;
    window.removeEventListener('resize', setPopover);
  };
  useEffect(() => {
    attachEvents();
    return () => detachEvents();
  });
  useEffect(() => {
    setPopover();
  }, [opened]);
  const popoverStyle = positions.set ? {
    ...(style || {}),
    left: positions.popoverLeft,
    top: positions.popoverTop
  } : style;
  const angleStyle = positions.set ? {
    left: positions.angleLeft,
    top: positions.angleTop
  } : undefined;
  const originClasses = {
    'top-right': 'origin-bottom-left',
    'top-left': 'origin-bottom-right',
    'middle-left': 'origin-right',
    'middle-right': 'origin-left',
    'bottom-right': 'origin-top-left',
    'bottom-left': 'origin-top-right'
  };
  const classes = cls(c.base[state], theme === 'material' && originClasses[positions.popoverPosition]);
  return /*#__PURE__*/React.createElement(React.Fragment, null, backdrop && /*#__PURE__*/React.createElement("div", {
    className: c.backdrop[state],
    onClick: onBackdropClick
  }), /*#__PURE__*/React.createElement(Component, _extends({
    ref: elRef,
    className: classes,
    style: popoverStyle
  }, attrs), angle && /*#__PURE__*/React.createElement("div", {
    ref: angleElRef,
    style: angleStyle,
    className: c.angleWrap[positions.anglePosition]
  }, /*#__PURE__*/React.createElement("div", {
    className: c.angleArrow[positions.anglePosition]
  })), /*#__PURE__*/React.createElement("div", {
    className: c.inner
  }, children)));
});
Popover.displayName = 'Popover';
export default Popover;

// vue/components/Popover.vue
<template>
  <div v-if="backdrop" :class="c.backdrop[state]" @click="onBackdropClick" />
  <component :is="component" ref="elRef" :style="popoverStyle" :class="classes">
    <div
      v-if="angle"
      ref="angleElRef"
      :style="angleStyle"
      :class="c.angleWrap[positions.anglePosition]"
    >
      <div :class="c.angleArrow[positions.anglePosition]" />
    </div>
    <div :class="c.inner"><slot /></div>
  </component>
</template>
<script>
  /* eslint-disable no-restricted-globals */

  import { ref, computed, onMounted, onBeforeUnmount, watch } from 'vue';

  import { cls } from '../../shared/esm/cls.js';

  import { themeClasses } from '../shared/use-theme-classes.js';

  import { useContext } from '../shared/use-context.js';
  import { useTheme } from '../shared/use-theme.js';

  import { calcPopoverPosition } from '../../shared/esm/calc-popover-position.js';

  import { darkClasses } from '../shared/use-dark-classes.js';

  import { PopoverClasses } from '../../shared/esm/classes/PopoverClasses.js';

  import { PopoverColors } from '../../shared/esm/colors/PopoverColors.js';

  export default {
    name: 'k-popover',
    props: {
      component: {
        type: String,
        default: 'div',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      size: { type: String, default: 'w-64' },
      opened: Boolean,
      backdrop: { type: Boolean, default: true },
      angle: { type: Boolean, default: true },
      angleClass: { type: String, default: '' },
      target: { type: [Object, String], default: undefined },
      targetX: { type: Number, default: undefined },
      targetY: { type: Number, default: undefined },
      targetWidth: { type: Number, default: undefined },
      targetHeight: { type: Number, default: undefined },
      translucent: { type: Boolean, default: true },
    },
    emits: ['backdropclick'],
    setup(props, ctx) {
      const context = useContext();
      const useDarkClasses = darkClasses(context);
      const useThemeClasses = themeClasses(context);
      const elRef = ref(null);
      const angleElRef = ref(null);
      const positions = ref({
        set: false,
        angleTop: 0,
        angleLeft: 0,
        anglePosition: 'bottom',
        popoverTop: 0,
        popoverLeft: 0,
        popoverPosition: 'top-left',
      });
      const theme = useTheme(props, context);

      const state = computed(() => (props.opened ? 'opened' : 'closed'));

      const colors = computed(() =>
        PopoverColors(props.colors || {}, useDarkClasses)
      );

      const c = useThemeClasses(props, () =>
        PopoverClasses(props, colors.value, ctx.attrs.class)
      );

      const setPopover = () => {
        if (!props.target || !elRef.value || !props.opened) return;
        positions.value = calcPopoverPosition({
          popoverEl: elRef.value,
          targetEl: props.target,
          angleEl: angleElRef.value,
          needsAngle: props.angle,
          targetX: props.targetX,
          targetY: props.targetY,
          targetWidth: props.targetWidth,
          targetHeight: props.targetHeight,
          theme: theme.value,
        });
      };

      const attachEvents = () => {
        if (typeof window === 'undefined') return;
        window.addEventListener('resize', setPopover);
      };

      const detachEvents = () => {
        if (typeof window === 'undefined') return;
        window.removeEventListener('resize', setPopover);
      };

      onMounted(() => {
        attachEvents();
        if (props.opened) setPopover();
      });
      onBeforeUnmount(() => {
        detachEvents();
      });

      watch(
        () => props.opened,
        () => setPopover()
      );

      const onBackdropClick = (e) => {
        ctx.emit('backdropclick', e);
      };

      const popoverStyle = computed(() =>
        positions.value.set
          ? {
              left: positions.value.popoverLeft,
              top: positions.value.popoverTop,
            }
          : {}
      );

      const angleStyle = computed(() =>
        positions.value.set
          ? {
              left: positions.value.angleLeft,
              top: positions.value.angleTop,
            }
          : undefined
      );

      const originClasses = {
        'top-right': 'origin-bottom-left',
        'top-left': 'origin-bottom-right',
        'middle-left': 'origin-right',
        'middle-right': 'origin-left',
        'bottom-right': 'origin-top-left',
        'bottom-left': 'origin-top-right',
      };
      const classes = computed(() =>
        cls(
          c.value.base[state.value],
          theme.value === 'material' &&
            originClasses[positions.value.popoverPosition],
          ctx.attrs.class
        )
      );

      return {
        onBackdropClick,
        c,
        state,
        elRef,
        angleElRef,
        classes,
        popoverStyle,
        needsAngle: props.angle,
        angleStyle,
        positions,
        theme,
      };
    },
  };
</script>
