// react/esm/components/Preloader.js
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
import React, { useRef, forwardRef, useImperativeHandle } from 'react';
import { useTheme } from '../shared/use-theme.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import PreloaderIOS from './icons/PreloaderIOS.js';
import PreloaderMaterial from './icons/PreloaderMaterial.js';
import { PreloaderClasses } from '../../../shared/esm/classes/PreloaderClasses.js';
import { PreloaderColors } from '../../../shared/esm/colors/PreloaderColors.js';
const Preloader = /*#__PURE__*/forwardRef((props, ref) => {
  const {
    component = 'span',
    className,
    colors: colorsProp,
    size = 'w-8 h-8',
    ios,
    material,
    // Children
    children,
    // Rest
    ...rest
  } = props;
  const elRef = useRef(null);
  useImperativeHandle(ref, () => ({
    el: elRef.current
  }));
  const Component = component;
  const attrs = {
    ...rest
  };
  const theme = useTheme({
    ios,
    material
  });
  const themeClasses = useThemeClasses({
    ios,
    material
  });
  const dark = useDarkClasses();
  const colors = PreloaderColors(colorsProp, dark);
  const SVGComponent = theme === 'ios' ? PreloaderIOS : PreloaderMaterial;
  const c = themeClasses(PreloaderClasses({
    ...props,
    size
  }, colors, theme), className);
  return /*#__PURE__*/React.createElement(Component, _extends({
    ref: elRef,
    className: c.base
  }, attrs), /*#__PURE__*/React.createElement("span", {
    className: c.inner
  }, /*#__PURE__*/React.createElement(SVGComponent, {
    className: "w-full h-full"
  })), children);
});
Preloader.displayName = 'Preloader';
export default Preloader;

// vue/components/Preloader.vue
<template>
  <component :is="component" :class="c.base">
    <span :class="c.inner">
      <component :is="svgComponent" class="w-full h-full" />
    </span>
    <slot />
  </component>
</template>
<script>
  import { computed } from 'vue';
  import { useContext } from '../shared/use-context.js';

  import { useTheme } from '../shared/use-theme.js';

  import { themeClasses } from '../shared/use-theme-classes.js';

  import { darkClasses } from '../shared/use-dark-classes.js';

  import PreloaderIOS from './icons/PreloaderIOS.vue';
  import PreloaderMaterial from './icons/PreloaderMaterial.vue';

  import { PreloaderClasses } from '../../shared/esm/classes/PreloaderClasses.js';

  import { PreloaderColors } from '../../shared/esm/colors/PreloaderColors.js';

  export default {
    name: 'k-preloader',
    props: {
      component: {
        type: String,
        default: 'span',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      size: {
        type: String,
        default: 'w-8 h-8',
      },
    },
    setup(props) {
      const context = useContext();
      const useDarkClasses = darkClasses(context);
      const useThemeClasses = themeClasses(context);
      const theme = useTheme(props, context);

      const colors = computed(() =>
        PreloaderColors(props.colors || {}, useDarkClasses)
      );

      const svgComponent = computed(() =>
        theme.value === 'ios' ? PreloaderIOS : PreloaderMaterial
      );

      const c = useThemeClasses(props, () =>
        PreloaderClasses(props, colors.value, theme.value)
      );

      return {
        svgComponent,
        c,
      };
    },
  };
</script>
